Repository corda/corda-docs, pull requests merged in 2020-11, with the labels that each got.

#307 EG-4127: renaming a file and fixing broken links
  content/en/docs/corda-enterprise/4.6/node/deploy/env-prod-test.md
  content/en/docs/corda-enterprise/4.6/operations/deployment/corda-firewall-configuration-fields.md
  content/en/docs/corda-enterprise/4.6/operations/deployment/env-prod-test.md
  content/en/docs/corda-enterprise/4.6/operations/deployment/firewall-deployment.md
  content/en/docs/corda-enterprise/4.6/release-notes-enterprise.md
Labels: do not merge yet!, internal, team technical writing

#308 EG-4300: css tweaks and some file restructuring
  themes/hugo-r3-theme/layouts/index.html
  themes/hugo-r3-theme/layouts/partials/head.html
  themes/hugo-r3-theme/layouts/partials/homehead.html
Labels: internal, team technical writing

#310 EG-4340: Correcting default value of bridgeConnectionTTLSeconds
  content/en/docs/corda-enterprise/4.6/operations/deployment/corda-firewall-configuration-fields.md
Labels: internal

#311 [EG-4375] Updating version reference in a command
  content/en/docs/corda-enterprise/4.5/docker-image.md
  content/en/docs/corda-enterprise/4.6/docker-image.md
  content/en/docs/corda-os/4.5/docker-image.md
  content/en/docs/corda-os/4.6/docker-image.md
Labels: internal, team technical writing

#309 EG-4008: make the home page tabs sticky
  themes/hugo-r3-theme/layouts/index.html
  themes/hugo-r3-theme/layouts/partials/homehead.html
Labels: internal, team technical writing

#306 EG-4213: clarify crlCheckArtemisServer setting usage
  content/en/docs/corda-enterprise/4.5/node/setup/corda-configuration-fields.md
  content/en/docs/corda-enterprise/4.5/operations/deployment/corda-configuration-fields.md
  content/en/docs/corda-enterprise/4.6/node/setup/corda-configuration-fields.md
  content/en/docs/corda-enterprise/4.6/operations/deployment/corda-configuration-fields.md
Labels: internal, team r3ers, team technical writing

#313 EG-4263: adding link from Metering Collection Tool page to Metering Client page
  content/en/docs/corda-enterprise/4.6/metering-collector.md
Labels: internal, team technical writing

#312 EG-4172: restructuring the corda firewall configuration documentation
  content/en/docs/corda-enterprise/4.2/corda-firewall-configuration-fields.md
  content/en/docs/corda-enterprise/4.2/corda-firewall-configuration-file.md
  content/en/docs/corda-enterprise/4.3/corda-firewall-configuration-fields.md
  content/en/docs/corda-enterprise/4.3/corda-firewall-configuration-file.md
  content/en/docs/corda-enterprise/4.4/node/corda-firewall-configuration-fields.md
  content/en/docs/corda-enterprise/4.4/node/corda-firewall-configuration-file.md
  content/en/docs/corda-enterprise/4.5/node/corda-firewall-configuration-fields.md
  content/en/docs/corda-enterprise/4.5/node/corda-firewall-configuration-file.md
  content/en/docs/corda-enterprise/4.5/operations/deployment/corda-firewall-configuration-fields.md
  content/en/docs/corda-enterprise/4.5/operations/deployment/corda-firewall-configuration-file.md
  content/en/docs/corda-enterprise/4.5/operations/deployment/firewall-deployment.md
  content/en/docs/corda-enterprise/4.6/node/corda-firewall-configuration-fields.md
  content/en/docs/corda-enterprise/4.6/node/corda-firewall-configuration-file.md
Labels: internal, team technical writing

#315 INFRA-946 Update artifact repository URLs
  content/en/docs/corda-enterprise/3.0/azure-vm.md
  content/en/docs/corda-enterprise/3.1/azure-vm.md
  content/en/docs/corda-enterprise/3.2/azure-vm.md
  content/en/docs/corda-enterprise/3.3/azure-vm.md
  content/en/docs/corda-enterprise/3.3/testnet-explorer.md
  content/en/docs/corda-enterprise/4.0/testnet-explorer.md
  content/en/docs/corda-enterprise/4.1/network-builder.md
  content/en/docs/corda-enterprise/4.1/testnet-explorer.md
  content/en/docs/corda-enterprise/4.2/testnet-explorer.md
  content/en/docs/corda-enterprise/4.5/cordapps/token-sdk-introduction.md
  content/en/docs/corda-enterprise/4.6/cordapps/token-sdk-introduction.md
  content/en/docs/corda-os/3.2/network-builder.md
  content/en/docs/corda-os/3.3/azure-vm.md
  content/en/docs/corda-os/3.3/network-builder.md
  content/en/docs/corda-os/3.4/azure-vm.md
  content/en/docs/corda-os/3.4/network-builder.md
  content/en/docs/corda-os/4.0/azure-vm.md
  content/en/docs/corda-os/4.0/network-builder.md
  content/en/docs/corda-os/4.0/testnet-explorer-corda.md
  content/en/docs/corda-os/4.5/token-sdk-introduction.md
  content/en/docs/corda-os/4.6/token-sdk-introduction.md
Labels: internal, team infra, team technical writing

#319 [EG-4036] Checksum files for CE 4.6.1, CENM 1.4.1, 1.3.2, 1.2.3
  content/en/docs/cenm/1.2/release-checksum-cenm.md
  content/en/docs/cenm/1.3/release-checksum-cenm.md
  content/en/docs/cenm/1.4/release-checksum-cenm.md
  content/en/docs/corda-enterprise/4.6/release-checksum-enterprise.md
Labels: internal, team technical writing

#318 EG-1619: improving layout of comparison matrices
  content/en/docs/corda-enterprise/4.4/_index.md
  content/en/docs/corda-enterprise/4.5/_index.md
  content/en/docs/corda-enterprise/4.6/_index.md
Labels: internal, team technical writing

#323 Update CE 4.4.4 release-checksum-enterprise.md
  content/en/docs/corda-enterprise/4.4/release-checksum-enterprise.md
Labels: internal, release patch, team technical writing

#324 Update CE 4.3.5 release-checksum-enterprise.md
  content/en/docs/corda-enterprise/4.3/release-checksum-enterprise.md
Labels: internal, release patch, team technical writing

#325 Update CE 4.5.2 release-checksum-enterprise.md
  content/en/docs/corda-enterprise/4.5/release-checksum-enterprise.md
Labels: internal, release patch, team technical writing

#320 EG 4017 Patch releases Q4 2020 - release notes, checksum pages, legal info pages
  content/en/docs/cenm/1.2/legal-info-1.2.0.md
  content/en/docs/cenm/1.2/legal-info-1.2.2.md
  content/en/docs/cenm/1.2/legal-info-1.2.3.md
  content/en/docs/cenm/1.2/release-checksum-cenm.md
  content/en/docs/cenm/1.2/release-notes.md
  content/en/docs/cenm/1.3/legal-info-1.3.0.md
  content/en/docs/cenm/1.3/legal-info-1.3.1.md
  content/en/docs/cenm/1.3/legal-info-1.3.2.md
  content/en/docs/cenm/1.3/release-checksum-cenm.md
  content/en/docs/cenm/1.3/release-notes.md
  content/en/docs/cenm/1.4/legal-info-1.4.0.md
  content/en/docs/cenm/1.4/legal-info-1.4.1.md
  content/en/docs/cenm/1.4/release-checksum-cenm.md
  content/en/docs/cenm/1.4/release-notes.md
  content/en/docs/corda-enterprise/3.3/legal-info.md
  content/en/docs/corda-enterprise/3.3/release-checksum-enterprise.md
  content/en/docs/corda-enterprise/3.3/release-notes.md
  content/en/docs/corda-enterprise/4.0/legal-info.md
  content/en/docs/corda-enterprise/4.0/release-checksum-enterprise.md
  content/en/docs/corda-enterprise/4.0/release-notes-enterprise.md
  content/en/docs/corda-enterprise/4.1/legal-info.md
  content/en/docs/corda-enterprise/4.1/release-checksum-enterprise.md
  content/en/docs/corda-enterprise/4.1/release-notes-enterprise.md
  content/en/docs/corda-enterprise/4.2/legal-info-4.2.0.md
  content/en/docs/corda-enterprise/4.2/legal-info-4.2.2.md
  content/en/docs/corda-enterprise/4.2/release-checksum-enterprise.md
  content/en/docs/corda-enterprise/4.2/release-notes-enterprise.md
  content/en/docs/corda-enterprise/4.3/legal-info-4.3.0.md
  content/en/docs/corda-enterprise/4.3/legal-info-4.3.5.md
  content/en/docs/corda-enterprise/4.3/release-checksum-enterprise.md
  content/en/docs/corda-enterprise/4.3/release-notes-enterprise.md
  content/en/docs/corda-enterprise/4.4/legal-info-4.4.0.md
  content/en/docs/corda-enterprise/4.4/legal-info-4.4.4.md
  content/en/docs/corda-enterprise/4.4/release-checksum-enterprise.md
  content/en/docs/corda-enterprise/4.4/release-notes-enterprise.md
  content/en/docs/corda-enterprise/4.5/legal-info-4.5.0.md
  content/en/docs/corda-enterprise/4.5/legal-info-4.5.2.md
  content/en/docs/corda-enterprise/4.5/release-checksum-enterprise.md
  content/en/docs/corda-enterprise/4.5/release-notes-enterprise.md
  content/en/docs/corda-enterprise/4.6/legal-info-4.6.0.md
  content/en/docs/corda-enterprise/4.6/legal-info-4.6.1.md
  content/en/docs/corda-enterprise/4.6/release-checksum-enterprise.md
  content/en/docs/corda-enterprise/4.6/release-notes-enterprise.md
  resources/checksums/resource-checksums-file-cenm-1.3.1.md
  resources/checksums/resource-checksums-file-cenm-1.3.md
  resources/checksums/resource-checksums-file-corda-enterprise-4.3.4.md
  resources/checksums/resource-checksums-file-corda-enterprise-4.4.3.md
  resources/checksums/resource-checksums-file-corda-enterprise-4.5.1.md
  resources/checksums/resource-checksums-file-corda-enterprise-4.5.md
  resources/checksums/resource-checksums-file-corda-os-4.5.md
Labels: internal, release patch, team technical writing

#273 EG-4065 Updated default timeout value from 10000 ms to 30000 ms [CENM 1.4.1]
  content/en/docs/cenm/1.4/database-set-up.md
  content/en/docs/cenm/1.4/network-map.md
  content/en/docs/cenm/1.4/signing-service.md
  content/en/docs/cenm/1.4/upgrade-notes.md
Labels: internal, team cenm, team technical writing

#326 EG-4485: fix CE 4.2 menu
  content/en/docs/corda-enterprise/4.2/deploy/ops-environment.md
  content/en/docs/corda-enterprise/4.2/operating/cm-backup.md
  content/en/docs/corda-enterprise/4.2/operating/cm-updating-cordapp.md
  content/en/docs/corda-enterprise/4.2/operating/cm-upgrading-node.md
Labels: internal, team technical writing

#327 EG-4038 Fixed broken link and added new links on the home page for the CENM 1.4
  themes/hugo-r3-theme/layouts/index.html
Labels: internal, team technical writing

#328 EG-2146: correcting configuration field information (and a couple of …
  content/en/docs/corda-enterprise/4.3/corda-configuration-file.md
  content/en/docs/corda-enterprise/4.4/node/setup/corda-configuration-file.md
  content/en/docs/corda-enterprise/4.5/node/setup/corda-configuration-file.md
  content/en/docs/corda-enterprise/4.5/operations/deployment/corda-configuration-file.md
  content/en/docs/corda-enterprise/4.6/node/setup/corda-configuration-file.md
  content/en/docs/corda-enterprise/4.6/operations/deployment/corda-configuration-file.md
  content/en/docs/corda-os/4.4/corda-configuration-file.md
  content/en/docs/corda-os/4.5/corda-configuration-file.md
  content/en/docs/corda-os/4.6/corda-configuration-file.md
Labels: bug, internal

#329 EG-3734: moving pages from network to nodes
  content/en/docs/corda-enterprise/4.4/docker-image.md
  content/en/docs/corda-enterprise/4.4/node-cloud.md
  content/en/docs/corda-enterprise/4.5/docker-image.md
  content/en/docs/corda-enterprise/4.5/node-cloud.md
  content/en/docs/corda-enterprise/4.6/docker-image.md
  content/en/docs/corda-enterprise/4.6/node-cloud.md
Labels: bug, internal, team technical writing

#330 EG-1915: Fixed formatting issues across performance testing pages. Fixed forma…
  content/en/docs/corda-enterprise/4.3/performance-testing/installation.md
  content/en/docs/corda-enterprise/4.3/performance-testing/introduction.md
  content/en/docs/corda-enterprise/4.3/performance-testing/jmeter-samplers.md
  content/en/docs/corda-enterprise/4.3/performance-testing/jmeter-testplans.md
  content/en/docs/corda-enterprise/4.3/performance-testing/performance-tuning.md
  content/en/docs/corda-enterprise/4.3/performance-testing/practical-considerations.md
  content/en/docs/corda-enterprise/4.3/performance-testing/r3-performance-runs.md
  content/en/docs/corda-enterprise/4.3/performance-testing/running-jmeter-corda.md
  content/en/docs/corda-enterprise/4.4/performance-testing/installation.md
  content/en/docs/corda-enterprise/4.4/performance-testing/introduction.md
  content/en/docs/corda-enterprise/4.4/performance-testing/jmeter-samplers.md
  content/en/docs/corda-enterprise/4.4/performance-testing/jmeter-testplans.md
  content/en/docs/corda-enterprise/4.4/performance-testing/performance-tuning.md
  content/en/docs/corda-enterprise/4.4/performance-testing/practical-considerations.md
  content/en/docs/corda-enterprise/4.4/performance-testing/r3-performance-runs.md
  content/en/docs/corda-enterprise/4.4/performance-testing/running-jmeter-corda.md
  content/en/docs/corda-enterprise/4.5/node/setup/corda-configuration-fields.md
  content/en/docs/corda-enterprise/4.5/performance-testing/installation.md
  content/en/docs/corda-enterprise/4.5/performance-testing/introduction.md
  content/en/docs/corda-enterprise/4.5/performance-testing/jmeter-samplers.md
  content/en/docs/corda-enterprise/4.5/performance-testing/jmeter-testplans.md
  content/en/docs/corda-enterprise/4.5/performance-testing/performance-results.md
  content/en/docs/corda-enterprise/4.5/performance-testing/performance-tuning.md
  content/en/docs/corda-enterprise/4.5/performance-testing/practical-considerations.md
  content/en/docs/corda-enterprise/4.5/performance-testing/r3-performance-runs.md
  content/en/docs/corda-enterprise/4.5/performance-testing/running-jmeter-corda.md
  content/en/docs/corda-enterprise/4.6/node/setup/corda-configuration-fields.md
  content/en/docs/corda-enterprise/4.6/performance-testing/installation.md
  content/en/docs/corda-enterprise/4.6/performance-testing/introduction.md
  content/en/docs/corda-enterprise/4.6/performance-testing/jmeter-samplers.md
  content/en/docs/corda-enterprise/4.6/performance-testing/jmeter-testplans.md
  content/en/docs/corda-enterprise/4.6/performance-testing/performance-results.md
  content/en/docs/corda-enterprise/4.6/performance-testing/performance-tuning.md
  content/en/docs/corda-enterprise/4.6/performance-testing/practical-considerations.md
  content/en/docs/corda-enterprise/4.6/performance-testing/r3-performance-runs.md
  content/en/docs/corda-enterprise/4.6/performance-testing/running-jmeter-corda.md
Labels: bug, internal, team technical writing

#333 EG- 4193: Improved documentation on shell commands in the node.
  content/en/docs/corda-enterprise/4.3/shell.md
  content/en/docs/corda-enterprise/4.4/node/operating/shell.md
  content/en/docs/corda-enterprise/4.5/node/operating/shell.md
  content/en/docs/corda-enterprise/4.6/node/operating/shell.md
  content/en/docs/corda-enterprise/codesamples/healthcheck-runtimeInfo.txt
  content/en/docs/corda-os/4.3/shell.md
  content/en/docs/corda-os/4.4/shell.md
  content/en/docs/corda-os/4.5/shell.md
  content/en/docs/corda-os/4.6/shell.md
  content/en/docs/corda-os/codesamples/healthcheck-runtimeInfo.txt
Labels: documentation, team technical writing

#335 fixed
  content/en/docs/corda-enterprise/4.5/cordapps/token-sdk-introduction.md
  content/en/docs/corda-enterprise/4.6/cordapps/token-sdk-introduction.md
  content/en/docs/corda-os/4.5/token-sdk-introduction.md
  content/en/docs/corda-os/4.6/token-sdk-introduction.md
Labels: bug

#340 EG-1436: Fixed missing links.
  content/en/docs/corda-enterprise/4.4/node/operating/node-database-developer.md
  content/en/docs/corda-enterprise/4.5/node/operating/node-database-developer.md
  content/en/docs/corda-enterprise/4.6/node/operating/node-database-developer.md
Labels: bug, internal, team technical writing

#344 EG-3630: Fixed broken links.
  content/en/docs/corda-enterprise/4.5/node/setup/host-prereq.md
  content/en/docs/corda-enterprise/4.6/node/setup/host-prereq.md
Labels: bug, internal, team technical writing

#343 EG-3664: Fixed broken link.
  content/en/docs/corda-enterprise/4.5/operations/deployment/host-prereq.md
Labels: bug, internal, team technical writing

#342 EG-4534: Fixed broken links.
  content/en/docs/corda-os/4.6/supplementary-tutorials-index.md
Labels: bug, internal, team technical writing

#341 EG-1318: Removed incorrect note on future availability of standalone message b…
  content/en/docs/corda-enterprise/4.2/messaging.md
  content/en/docs/corda-enterprise/4.3/messaging.md
  content/en/docs/corda-enterprise/4.4/messaging.md
  content/en/docs/corda-enterprise/4.5/messaging.md
  content/en/docs/corda-enterprise/4.6/messaging.md
Labels: bug, internal, team technical writing

#339 EG-1402: Added correct links to sample CorDapp and tutorial on Network Bootstrapper page.
  content/en/docs/corda-enterprise/4.4/network-bootstrapper.md
  content/en/docs/corda-enterprise/4.5/network-bootstrapper.md
  content/en/docs/corda-enterprise/4.6/network-bootstrapper.md
  content/en/docs/corda-os/4.4/network-bootstrapper.md
  content/en/docs/corda-os/4.5/network-bootstrapper.md
  content/en/docs/corda-os/4.6/network-bootstrapper.md
Labels: bug, internal, team technical writing

#337 EG-3927: Added note to node documentation on node failure to restart when NMS …
  content/en/docs/corda-enterprise/4.4/node/deploy/starting-components.md
  content/en/docs/corda-enterprise/4.5/messaging.md
  content/en/docs/corda-enterprise/4.5/operations/deployment/starting-components.md
  content/en/docs/corda-enterprise/4.6/messaging.md
  content/en/docs/corda-enterprise/4.6/operations/deployment/starting-components.md
Labels: bug, internal, team technical writing

#345 Fix the Docker image name of cenm-cli
  content/en/docs/corda-enterprise/4.6/operations/deployment/deployment-kubernetes.md
Labels: internal, team r3ers

#336 EG-3129: Added missing links.
  content/en/docs/corda-enterprise/4.4/node-database-intro.md
  content/en/docs/corda-enterprise/4.5/node-database-intro.md
  content/en/docs/corda-enterprise/4.6/node-database-intro.md
Labels: bug, internal, team technical writing

#332 EG-3172: Added missing links in cryptoservice configuration document.
  content/en/docs/corda-enterprise/4.4/node/operating/cryptoservice-configuration.md
  content/en/docs/corda-enterprise/4.5/node/operating/cryptoservice-configuration.md
  content/en/docs/corda-enterprise/4.6/node/operating/cryptoservice-configuration.md
Labels: bug, team technical writing

#338 EG-3411: fixing multiple broken links
  content/en/docs/corda-enterprise/3.1/running-a-notary.md
  content/en/docs/corda-enterprise/3.2/running-a-notary.md
  content/en/docs/corda-enterprise/3.3/running-a-notary.md
  content/en/docs/corda-enterprise/4.0/running-a-notary.md
  content/en/docs/corda-enterprise/4.1/running-a-notary.md
  content/en/docs/corda-enterprise/4.2/running-a-notary.md
  content/en/docs/corda-enterprise/4.3/running-a-notary-cluster/handling-flag-days.md
  content/en/docs/corda-enterprise/4.3/running-a-notary.md
  content/en/docs/corda-enterprise/4.4/network-bootstrapper.md
  content/en/docs/corda-enterprise/4.4/node/operating/node-database-tables.md
  content/en/docs/corda-enterprise/4.4/notary/handling-flag-days.md
  content/en/docs/corda-enterprise/4.4/notary/running-a-notary.md
  content/en/docs/corda-enterprise/4.5/network-bootstrapper.md
  content/en/docs/corda-enterprise/4.5/node/operating/node-database-tables.md
  content/en/docs/corda-enterprise/4.5/notary/handling-flag-days.md
  content/en/docs/corda-enterprise/4.5/notary/running-a-notary.md
  content/en/docs/corda-enterprise/4.6/network-bootstrapper.md
  content/en/docs/corda-enterprise/4.6/node/operating/node-database-tables.md
Labels: bug, internal, team technical writing

#331 EG-3966: backporting note to 4.3, 4.4, and 4.5, repeating the note to…
  content/en/docs/corda-enterprise/4.3/metering-collector.md
  content/en/docs/corda-enterprise/4.4/metering-collector.md
  content/en/docs/corda-enterprise/4.5/metering-collector.md
  content/en/docs/corda-enterprise/4.6/metering-collector.md
Labels: bug, internal, team technical writing

#347 EG-363: Fixed broken link.
  content/en/docs/corda-enterprise/4.3/network-bootstrapper.md
  content/en/docs/corda-enterprise/4.4/network-bootstrapper.md
  content/en/docs/corda-enterprise/4.5/network-bootstrapper.md
  content/en/docs/corda-enterprise/4.6/network-bootstrapper.md
Labels: bug, internal, team technical writing

#350 EG-4193: Removed shell commands from OS documentation that are not in OS.
  content/en/docs/corda-os/4.3/shell.md
  content/en/docs/corda-os/4.4/shell.md
  content/en/docs/corda-os/4.5/shell.md
  content/en/docs/corda-os/4.6/shell.md
Labels: internal, team technical writing

#346 EG-4147: merging upgrade information into one file
  content/en/docs/corda-enterprise/4.6/node-upgrade-notes.md
  content/en/docs/corda-enterprise/4.6/node/operating/cm-upgrading-node.md
Labels: bug, internal, team technical writing

#348 EG-3857: Fixed broken links.
  content/en/docs/corda-os/4.4/network-map.md
  content/en/docs/corda-os/4.5/network-map.md
  content/en/docs/corda-os/4.6/network-map.md
Labels: bug, internal, team technical writing

#349 EG-4142: Fixed code snippet that was not rendering correctly.
  content/en/docs/corda-enterprise/4.5/cordapps/token-sdk-introduction.md
  content/en/docs/corda-enterprise/4.6/cordapps/token-sdk-introduction.md
Labels: bug, internal, team technical writing
