Repository corda/corda-docs, pull requests merged in 2020-09, with the labels that each got.

#212 EG-3735: Fixes incorrect guidance on obtaining network trust root
  content/en/docs/corda-enterprise/4.5/node/deploy/env-prod-test.md
  content/en/docs/corda-enterprise/4.5/operations/deployment/env-prod-test.md
Labels: internal, team r3ers, team technical writing

#209 EG-3648: adding GO statement to Azure SQL scripts
  content/en/docs/corda-enterprise/4.0/node-database.md
  content/en/docs/corda-enterprise/4.2/node-database-admin.md
  content/en/docs/corda-enterprise/4.3/node-database-admin.md
  content/en/docs/corda-enterprise/4.4/node/operating/node-database-admin.md
  content/en/docs/corda-enterprise/4.5/node/operating/node-database-admin.md
Labels: internal, team technical writing

#213 EG-3723 Updated Corda Testnet Intro pages for OS and CE 4.0 and above
  content/en/docs/corda-enterprise/4.0/corda-testnet-intro.md
  content/en/docs/corda-enterprise/4.1/corda-testnet-intro.md
  content/en/docs/corda-enterprise/4.2/corda-testnet-intro.md
  content/en/docs/corda-enterprise/4.3/corda-testnet-intro.md
  content/en/docs/corda-enterprise/4.4/network/corda-testnet-intro.md
  content/en/docs/corda-enterprise/4.5/network/corda-testnet-intro.md
  content/en/docs/corda-os/4.0/corda-testnet-intro.md
  content/en/docs/corda-os/4.1/corda-testnet-intro.md
  content/en/docs/corda-os/4.3/corda-testnet-intro.md
  content/en/docs/corda-os/4.4/corda-testnet-intro.md
  content/en/docs/corda-os/4.5/corda-testnet-intro.md
Labels: internal, team technical writing

#215 EG-3788: adding new shortcode files
  themes/hugo-r3-theme/layouts/shortcodes/codesample.html
  themes/hugo-r3-theme/layouts/shortcodes/figure.html
  themes/hugo-r3-theme/layouts/shortcodes/includefile.html
Labels: internal, team technical writing

#211 EG-3732: Fix reference node.conf, correct forward-looking statement, cross-link to node naming docs
  content/en/docs/corda-enterprise/4.5/node/setup/corda-configuration-fields.md
  content/en/docs/corda-enterprise/4.5/node/setup/corda-configuration-file.md
  content/en/docs/corda-enterprise/4.5/operations/deployment/corda-configuration-fields.md
  content/en/docs/corda-enterprise/4.5/operations/deployment/corda-configuration-file.md
  content/en/docs/corda-os/4.5/corda-configuration-fields.md
Labels: internal, team r3ers, team technical writing

#216 EG-3731: removing leftover ':doc:' directives and some formatting fixes.
  content/en/docs/cenm/1.1/upgrade-notes.md
  content/en/docs/corda-enterprise/4.3/corda-configuration-file.md
  content/en/docs/corda-enterprise/4.4/node/setup/corda-configuration-file.md
  content/en/docs/corda-enterprise/4.5/node/setup/corda-configuration-fields.md
  content/en/docs/corda-enterprise/4.5/operations/deployment/corda-configuration-fields.md
  content/en/docs/corda-os/4.4/corda-configuration-file.md
Labels: internal, team technical writing

#214 EG-2919: removing SQL section
  content/en/docs/corda-os/4.5/node-database.md
Labels: internal, team technical writing

#218 EG-3885 Set search hits number to 30
  themes/hugo-r3-theme/layouts/partials/scripts-docs.html
  themes/hugo-r3-theme/scripts/vendor/doc-search.js
Labels: internal, team technical writing

#221 EG-3661 Add Kotlin instructions on Running a sample CorDapp page
  content/en/docs/corda-enterprise/4.4/cordapps/tutorial-cordapp.md
  content/en/docs/corda-enterprise/4.5/cordapps/tutorial-cordapp.md
  content/en/docs/corda-os/4.4/tutorial-cordapp.md
  content/en/docs/corda-os/4.5/tutorial-cordapp.md
Labels: internal, team technical writing

#222 CORDA-3610 Removed false statement from Writing a CorDapp page for OS 4.4 and 4.5
  content/en/docs/corda-enterprise/4.4/cordapps/writing-a-cordapp.md
  content/en/docs/corda-enterprise/4.5/cordapps/writing-a-cordapp.md
  content/en/docs/corda-enterprise/4.5/performance-testing/performance-results.md
  content/en/docs/corda-enterprise/4.5/performance-testing/toc-tree.md
  content/en/docs/corda-os/4.4/writing-a-cordapp.md
  content/en/docs/corda-os/4.5/writing-a-cordapp.md
Labels: internal, team technical writing

#223 EG-1639: Fixed code styling in Flow Framework Internals OS 4.4 and 4.5
  content/en/docs/corda-os/4.4/contributing-flow-internals.md
  content/en/docs/corda-os/4.5/contributing-flow-internals.md
Labels: internal, team technical writing

#224 EG-3908 Removed redundant links to the CENM private repo left over from migrated rst files
  content/en/docs/cenm/1.0/enm-with-ssl.md
  content/en/docs/cenm/1.0/pki-guide.md
  content/en/docs/cenm/1.0/quick-start.md
  content/en/docs/cenm/1.0/signing-service.md
  content/en/docs/cenm/1.0/workflow.md
  content/en/docs/cenm/1.1/config-obfuscation-tool.md
  content/en/docs/cenm/1.1/enm-with-ssl.md
  content/en/docs/cenm/1.1/identity-manager.md
  content/en/docs/cenm/1.1/network-map.md
  content/en/docs/cenm/1.1/pki-guide.md
  content/en/docs/cenm/1.1/pki-tool.md
  content/en/docs/cenm/1.1/quick-start.md
  content/en/docs/cenm/1.1/shell.md
  content/en/docs/cenm/1.1/signing-service.md
  content/en/docs/cenm/1.1/workflow.md
  content/en/docs/cenm/1.2/config-obfuscation-tool.md
  content/en/docs/cenm/1.2/ejbca-plugin.md
  content/en/docs/cenm/1.2/enm-with-ssl.md
  content/en/docs/cenm/1.2/identity-manager.md
  content/en/docs/cenm/1.2/network-map.md
  content/en/docs/cenm/1.2/pki-guide.md
  content/en/docs/cenm/1.2/pki-tool.md
  content/en/docs/cenm/1.2/quick-start.md
  content/en/docs/cenm/1.2/shell.md
  content/en/docs/cenm/1.2/signing-service.md
  content/en/docs/cenm/1.2/workflow.md
  content/en/docs/cenm/1.3/ejbca-plugin.md
  content/en/docs/cenm/1.3/enm-with-ssl.md
  content/en/docs/cenm/1.3/pki-guide.md
  content/en/docs/cenm/1.3/pki-tool.md
  content/en/docs/cenm/1.3/shell.md
  content/en/docs/cenm/1.3/signing-service.md
  content/en/docs/cenm/1.3/workflow.md
Labels: internal, team cenm, team technical writing

#225 EG-3923: fixing broken link
  content/en/docs/corda-enterprise/4.5/release-notes-enterprise.md
Labels: internal, team technical writing

#227 EG-3917 Removed the page about one-click deployment and respective RN section
  content/en/docs/corda-enterprise/4.5/node/deploy/one-click-deployment.md
  content/en/docs/corda-enterprise/4.5/release-notes-enterprise.md
Labels: internal, team technical writing

#232 EG-2735 Removed duplicate serialisation section from multiple versions
  content/en/docs/corda-enterprise/4.0/upgrading-cordapps.md
  content/en/docs/corda-enterprise/4.2/upgrading-cordapps.md
  content/en/docs/corda-enterprise/4.3/upgrading-cordapps.md
  content/en/docs/corda-enterprise/4.4/cordapps/upgrading-cordapps.md
  content/en/docs/corda-enterprise/4.5/cordapps/upgrading-cordapps.md
  content/en/docs/corda-os/4.3/upgrading-cordapps.md
  content/en/docs/corda-os/4.4/upgrading-cordapps.md
  content/en/docs/corda-os/4.5/upgrading-cordapps.md
Labels: internal, team technical writing

#233 EG-2800 Removed redundant sentence in API Testing page - all versions up to CE/OS 4.5
  content/en/docs/corda-enterprise/3.0/api-testing.md
  content/en/docs/corda-enterprise/3.1/api-testing.md
  content/en/docs/corda-enterprise/3.2/api-testing.md
  content/en/docs/corda-enterprise/3.3/api-testing.md
  content/en/docs/corda-enterprise/4.0/api-testing.md
  content/en/docs/corda-enterprise/4.1/api-testing.md
  content/en/docs/corda-enterprise/4.2/api-testing.md
  content/en/docs/corda-enterprise/4.3/api-testing.md
  content/en/docs/corda-enterprise/4.4/cordapps/api-testing.md
  content/en/docs/corda-enterprise/4.5/cordapps/api-testing.md
  content/en/docs/corda-os/3.0/api-testing.md
  content/en/docs/corda-os/3.1/api-testing.md
  content/en/docs/corda-os/3.2/api-testing.md
  content/en/docs/corda-os/3.3/api-testing.md
  content/en/docs/corda-os/3.4/api-testing.md
  content/en/docs/corda-os/4.0/api-testing.md
  content/en/docs/corda-os/4.1/api-testing.md
  content/en/docs/corda-os/4.3/api-testing.md
  content/en/docs/corda-os/4.4/api-testing.md
  content/en/docs/corda-os/4.5/api-testing.md
Labels: internal, team technical writing

#241 EG-2091 Fixed a link in CE 4.4 enterprise release notes
  content/en/docs/corda-enterprise/4.4/release-notes-enterprise.md
Labels: internal, team technical writing

#238 EG-1451 Updated "CorDapps to newer Platform Versions" pages in OS/CE 4.4
  content/en/docs/corda-enterprise/4.4/app-upgrade-notes.md
  content/en/docs/corda-os/4.4/app-upgrade-notes.md
Labels: internal, team technical writing

#239 EG-2592 Fixed a typo in Running JMeter page for CE 4.0 to 4.4
  content/en/docs/corda-enterprise/4.0/performance-testing/running-jmeter-corda.md
  content/en/docs/corda-enterprise/4.1/performance-testing/running-jmeter-corda.md
  content/en/docs/corda-enterprise/4.2/performance-testing/running-jmeter-corda.md
  content/en/docs/corda-enterprise/4.3/performance-testing/running-jmeter-corda.md
  content/en/docs/corda-enterprise/4.4/performance-testing/running-jmeter-corda.md
Labels: internal, team technical writing

#243 EG-1617 Removed phantom embedded shell page from CE 4.4 doc set
  content/en/docs/corda-enterprise/4.4/shell.md
Labels: internal, team technical writing

#230 EG-2636 Removed incorrect note in maxMessageSize definition - CE/OS 4.0/4.5 & CENM 1.0/1.3
  content/en/docs/cenm/1.0/network-map-overview.md
  content/en/docs/cenm/1.1/network-map-overview.md
  content/en/docs/cenm/1.2/network-map-overview.md
  content/en/docs/cenm/1.3/network-map-overview.md
  content/en/docs/corda-enterprise/4.0/network-map.md
  content/en/docs/corda-enterprise/4.1/network-map.md
  content/en/docs/corda-enterprise/4.2/network-map.md
  content/en/docs/corda-enterprise/4.3/network-map.md
  content/en/docs/corda-enterprise/4.4/network/network-map.md
  content/en/docs/corda-enterprise/4.5/network/network-map.md
  content/en/docs/corda-os/4.0/network-map.md
  content/en/docs/corda-os/4.1/network-map.md
  content/en/docs/corda-os/4.3/network-map.md
  content/en/docs/corda-os/4.4/network-map.md
  content/en/docs/corda-os/4.5/network-map.md
Labels: internal, team technical writing

#228 EG-3806 Removed dead links to example-code dirs in dev repos from OS and CE 4.5 pages
  content/en/docs/corda-enterprise/4.5/app-upgrade-notes.md
  content/en/docs/corda-enterprise/4.5/cordapps/api-flows.md
  content/en/docs/corda-enterprise/4.5/cordapps/flow-cookbook.md
  content/en/docs/corda-enterprise/4.5/cordapps/state-persistence.md
  content/en/docs/corda-enterprise/4.5/flow-state-machines.md
  content/en/docs/corda-enterprise/4.5/node/operating/clientrpc.md
  content/en/docs/corda-enterprise/4.5/serialization.md
  content/en/docs/corda-os/4.5/api-flows.md
  content/en/docs/corda-os/4.5/api-persistence.md
  content/en/docs/corda-os/4.5/api-testing.md
  content/en/docs/corda-os/4.5/api-transactions.md
  content/en/docs/corda-os/4.5/app-upgrade-notes.md
  content/en/docs/corda-os/4.5/clientrpc.md
  content/en/docs/corda-os/4.5/contributing-flow-state-machines.md
  content/en/docs/corda-os/4.5/corda-configuration-file.md
  content/en/docs/corda-os/4.5/flow-cookbook.md
  content/en/docs/corda-os/4.5/flow-state-machines.md
  content/en/docs/corda-os/4.5/hello-world-flow.md
  content/en/docs/corda-os/4.5/hello-world-state.md
  content/en/docs/corda-os/4.5/serialization.md
  content/en/docs/corda-os/4.5/tut-two-party-contract.md
  content/en/docs/corda-os/4.5/tut-two-party-flow.md
  content/en/docs/corda-os/4.5/tutorial-building-transactions.md
  content/en/docs/corda-os/4.5/tutorial-clientrpc-api.md
  content/en/docs/corda-os/4.5/tutorial-contract.md
  content/en/docs/corda-os/4.5/tutorial-integration-testing.md
  content/en/docs/corda-os/4.5/tutorial-tear-offs.md
  content/en/docs/corda-os/4.5/tutorial-test-dsl.md
Labels: internal, team technical writing

#229 EG-3922 EG-3417 Added warning that network map and identity manager cannot be redirected - CENM 1.3
  content/en/docs/cenm/1.3/config-identity-manager-parameters.md
  content/en/docs/cenm/1.3/config-network-map-parameters.md
  content/en/docs/cenm/1.3/enm-components.md
  content/en/docs/cenm/1.3/identity-manager.md
  content/en/docs/cenm/1.3/network-map-overview.md
  content/en/docs/cenm/1.3/network-map.md
Labels: internal, team cenm, team technical writing

#234 EG-3658 Updated java version and clarified Zulu links in CENM 1.3 and CE 4.5 support matrix pages
  content/en/docs/cenm/1.3/cenm-support-matrix.md
  content/en/docs/corda-enterprise/4.5/platform-support-matrix.md
Labels: internal, team technical writing

#231 EG-2552 Updated note in k8s deployment page for CENM 1.2
  content/en/docs/cenm/1.2/deployment-kubernetes.md
Labels: internal, team cenm, team technical writing

#244 EG-3881 Updates to formatting in firewall upgrade pages for CE 4.0, CE 4.2, CE 4.3, and CE 4.5
  content/en/docs/corda-enterprise/4.0/corda-firewall-upgrade.md
  content/en/docs/corda-enterprise/4.2/corda-firewall-upgrade.md
  content/en/docs/corda-enterprise/4.3/corda-firewall-upgrade.md
  content/en/docs/corda-enterprise/4.5/node/corda-firewall-upgrade.md
Labels: internal, team technical writing

#235 EG-1271 Removed obsolete reference and updated paragraph formatting for packageOwnership
  content/en/docs/cenm/1.2/config-network-parameters.md
  content/en/docs/cenm/1.3/config-network-parameters.md
Labels: internal, team cenm, team technical writing

#237 EG-1613 EG-3935 Reinstated testnet explorer pages for OS/CE 4.5, and fixed TOC sections in Corda Networks pages for CE 4.4/4.5
  content/en/docs/corda-enterprise/4.4/network/corda-networks.md
  content/en/docs/corda-enterprise/4.5/network/corda-networks.md
  content/en/docs/corda-enterprise/4.5/network/testnet-explorer.md
  content/en/docs/corda-os/4.5/testnet-explorer-corda.md
Labels: internal, team technical writing

#236 EG-1614 Fixed hardcoded CENM link in CE 4.4 and 4.5 network map pages
  content/en/docs/corda-enterprise/4.4/network/network-map.md
  content/en/docs/corda-enterprise/4.5/network/network-map.md
Labels: internal, team technical writing

#242 EG-1667 Fixed bad anchor links in "Advanced CorDapp Concepts page" for CE 4.4 and CE 4.5
  content/en/docs/corda-enterprise/4.4/cordapp-advanced-concepts.md
  content/en/docs/corda-enterprise/4.5/cordapp-advanced-concepts.md
Labels: internal, team technical writing

#246 EG-3545: removing batchTimeoutMs from the notary section of these docs
  content/en/docs/corda-enterprise/4.3/corda-configuration-file.md
  content/en/docs/corda-enterprise/4.4/node/setup/corda-configuration-file.md
  content/en/docs/corda-enterprise/4.5/node/setup/corda-configuration-fields.md
  content/en/docs/corda-enterprise/4.5/operations/deployment/corda-configuration-fields.md
Labels: internal, team technical writing

#220 EG 2561: various updates to CENM docs
  content/en/docs/cenm/1.0/enm-components.md
  content/en/docs/cenm/1.1/enm-components.md
  content/en/docs/cenm/1.2/config-identity-manager-parameters.md
  content/en/docs/cenm/1.2/ejbca-plugin.md
  content/en/docs/cenm/1.2/enm-components.md
  content/en/docs/cenm/1.3/angel-service.md
  content/en/docs/cenm/1.3/config-identity-manager-parameters.md
  content/en/docs/cenm/1.3/ejbca-plugin.md
  content/en/docs/cenm/1.3/enm-components.md
  content/en/docs/cenm/1.3/enm-with-ssl.md
  content/en/docs/cenm/1.3/identity-manager.md
  content/en/docs/cenm/1.3/network-map.md
  content/en/docs/cenm/1.3/release-notes.md
  content/en/docs/cenm/1.3/signing-service.md
  content/en/docs/cenm/1.3/upgrade-notes.md
  content/en/docs/cenm/1.3/zone-service.md
  content/en/docs/corda-enterprise/4.4/network/corda-networks.md
  content/en/docs/corda-enterprise/4.5/network/corda-networks.md
  content/en/docs/corda-enterprise/4.5/operations/deployment/cenm-upgrade.md
Labels: internal, team cenm, team technical writing

#245 ENT-5745: clarifying the use of --config-file
  content/en/docs/corda-enterprise/4.1/node-commandline.md
  content/en/docs/corda-enterprise/4.2/node-commandline.md
  content/en/docs/corda-enterprise/4.3/node-commandline.md
  content/en/docs/corda-enterprise/4.4/node/node-commandline.md
  content/en/docs/corda-enterprise/4.5/node/node-commandline.md
  content/en/docs/corda-os/4.0/node-commandline.md
  content/en/docs/corda-os/4.1/node-commandline.md
  content/en/docs/corda-os/4.3/node-commandline.md
  content/en/docs/corda-os/4.4/node-commandline.md
  content/en/docs/corda-os/4.5/node-commandline.md
Labels: internal, team node internals, team technical writing

#247 EG-3905 Fixed typo in checkpoint tooling pages for CE 4.1 - 4.5
  content/en/docs/corda-enterprise/4.1/checkpoint-tooling.md
  content/en/docs/corda-enterprise/4.2/checkpoint-tooling.md
  content/en/docs/corda-enterprise/4.3/checkpoint-tooling.md
  content/en/docs/corda-enterprise/4.4/checkpoint-tooling.md
  content/en/docs/corda-enterprise/4.5/checkpoint-tooling.md
Labels: internal, team kernel, team technical writing

#249 EG-2842: Remove references to rewriteBatchedStatements and useSSL
  content/en/docs/corda-enterprise/4.4/notary/installing-the-notary-service.md
  content/en/docs/corda-enterprise/4.5/notary/installing-the-notary-service.md
Labels: internal, team notaries, team technical writing

#251 EG-4007 Fixed some typos
  themes/hugo-r3-theme/layouts/index.html
Labels: internal, team technical writing

#252 CORDA-3795 Added a CE 4.6 release note
  content/en/docs/corda-enterprise/4.6/release-notes-enterprise.md
Labels: internal, team kernel, team technical writing

#254 EG-4010: fixing behaviour of search on home page, and correcting a co…
  content/en/docs/corda-os/4.6/introduction/cordanodeadmin.md
  themes/hugo-r3-theme/layouts/index.html
Labels: internal, team technical writing

#256 EG-2976 Changes to TLS keys in HSM section as per feedback
  content/en/docs/corda-enterprise/4.6/ha-utilities.md
  content/en/docs/corda-enterprise/4.6/node/setup/corda-configuration-fields.md
  content/en/docs/corda-enterprise/4.6/node/setup/tls-keys-in-hsm.md
Labels: internal, team kernel, team technical writing

#257 EG-4007 Updates to home page strings
  themes/hugo-r3-theme/layouts/index.html
Labels: internal, team technical writing

#258 EG-4007 Fixed a link
  themes/hugo-r3-theme/layouts/index.html
Labels: internal, team technical writing
