Repository corda/corda-docs, pull requests merged in 2020-06, with the labels that each got.

#76 EG-1602 Fix code tabs
  themes/hugo-r3-theme/layouts/shortcodes/tabs.html
  themes/hugo-r3-theme/scripts/activate-tabs.js
  themes/hugo-r3-theme/static/js/app.js
  themes/hugo-r3-theme/static/js/app.js.map
  themes/hugo-r3-theme/static/js/vendor.js
  themes/hugo-r3-theme/static/js/vendor.js.map
Labels: internal, team notaries, team technical writing

#81 [EG-2120] Fixed typo in line #959
  content/en/docs/cenm/1.2/pki-guide.md
  content/en/docs/corda-os/4.4/api-vault-query.md
Labels: internal, team technical writing

#80 [EG-1600] Fix typo: line 376 now references PartyB
  content/en/docs/corda-os/4.4/tutorial-cordapp.md
Labels: internal, team technical writing

#82 [EG-2001] Fixing formatting issues
  content/en/docs/corda-enterprise/3.0/serialization-enum-evolution.md
  content/en/docs/corda-enterprise/3.1/serialization-enum-evolution.md
  content/en/docs/corda-enterprise/3.2/serialization-enum-evolution.md
  content/en/docs/corda-enterprise/3.3/serialization-enum-evolution.md
  content/en/docs/corda-enterprise/4.0/serialization-enum-evolution.md
  content/en/docs/corda-enterprise/4.1/serialization-enum-evolution.md
  content/en/docs/corda-enterprise/4.2/serialization-enum-evolution.md
  content/en/docs/corda-enterprise/4.3/serialization-enum-evolution.md
  content/en/docs/corda-enterprise/4.4/serialization-enum-evolution.md
  content/en/docs/corda-os/3.0/serialization-enum-evolution.md
  content/en/docs/corda-os/3.1/serialization-enum-evolution.md
  content/en/docs/corda-os/3.2/serialization-enum-evolution.md
  content/en/docs/corda-os/3.3/serialization-enum-evolution.md
  content/en/docs/corda-os/3.4/serialization-enum-evolution.md
  content/en/docs/corda-os/4.0/serialization-enum-evolution.md
  content/en/docs/corda-os/4.1/serialization-enum-evolution.md
  content/en/docs/corda-os/4.3/serialization-enum-evolution.md
  content/en/docs/corda-os/4.4/serialization-enum-evolution.md
Labels: internal, team technical writing

#83 EG-2463 Removing Inaccurate SQLServer information
  content/en/docs/corda-os/4.0/node-database.md
  content/en/docs/corda-os/4.1/node-database.md
  content/en/docs/corda-os/4.3/node-database.md
  content/en/docs/corda-os/4.4/node-database.md
Labels: internal, team technical writing

#84 [EG-1933] Added menu structure for /notary/faq section
  content/en/docs/corda-enterprise/4.4/notary/faq/eta-mechanism.md
  content/en/docs/corda-enterprise/4.4/notary/faq/notary-failover.md
  content/en/docs/corda-enterprise/4.4/notary/faq/notary-load-balancing.md
  content/en/docs/corda-enterprise/4.4/notary/faq/toctree.md
Labels: internal, team technical writing

#88 [EG-1600] Fixed curl command in Creating an IOU via the endpoint section
  content/en/docs/corda-enterprise/4.3/tutorial-cordapp.md
  content/en/docs/corda-os/4.3/tutorial-cordapp.md
Labels: internal, team technical writing

#90 EG-2208 Commit database schema after creation
  content/en/docs/cenm/1.1/database-set-up.md
  content/en/docs/cenm/1.2/database-set-up.md
Labels: internal, team cenm, team technical writing

#89 Andrewmc/EG_2435
  content/en/docs/corda-enterprise/3.1/node-database-access-h2.md
  content/en/docs/corda-enterprise/3.2/node-database-access-h2.md
  content/en/docs/corda-enterprise/3.3/node-database-access-h2.md
  content/en/docs/corda-enterprise/4.0/node-database-access-h2.md
  content/en/docs/corda-enterprise/4.2/node-database-access-h2.md
  content/en/docs/corda-enterprise/4.3/node-database-access-h2.md
  content/en/docs/corda-enterprise/4.4/node-database-access-h2.md
Labels: internal, team technical writing

#91 [EG-1518] Changed incorrect references to "input" to refer to"output"
  content/en/docs/corda-enterprise/4.3/quickstart-build.md
  content/en/docs/corda-enterprise/4.4/cordapps/quickstart-build.md
  content/en/docs/corda-os/4.1/quickstart-build.md
  content/en/docs/corda-os/4.3/quickstart-build.md
Labels: internal, team technical writing

#87 Maryforde/eg 2120
  content/en/docs/corda-enterprise/4.4/cordapps/api-vault-query.md
Labels: internal, team technical writing

#93 [EG-2501] Added navigation for features-versions.md to Corda OS 4.3, Corda OS 4.2 and Corda Enterprise 4.3
  content/en/docs/corda-enterprise/4.3/api-contract-constraints.md
  content/en/docs/corda-enterprise/4.3/features-versions.md
  content/en/docs/corda-enterprise/4.3/network-map.md
  content/en/docs/corda-enterprise/4.4/features-versions.md
  content/en/docs/corda-os/4.3/api-contract-constraints.md
  content/en/docs/corda-os/4.3/features-versions.md
  content/en/docs/corda-os/4.3/network-map.md
  content/en/docs/corda-os/4.4/api-contract-constraints.md
  content/en/docs/corda-os/4.4/features-versions.md
  content/en/docs/corda-os/4.4/network-map.md
Labels: internal, team technical writing

#94 [EG-1599] Fix formatting and broken link in CE release notes for 4.1
  content/en/docs/corda-enterprise/4.1/release-notes.md
Labels: internal, team technical writing

#92 [EG-2120] Minor typos on some pages
  content/en/docs/cenm/1.0/pki-guide.md
  content/en/docs/cenm/1.1/pki-guide.md
  content/en/docs/corda-enterprise/3.0/api-vault-query.md
  content/en/docs/corda-enterprise/3.1/api-vault-query.md
  content/en/docs/corda-enterprise/3.2/api-vault-query.md
  content/en/docs/corda-enterprise/3.3/api-vault-query.md
  content/en/docs/corda-enterprise/4.0/api-vault-query.md
  content/en/docs/corda-enterprise/4.1/api-vault-query.md
  content/en/docs/corda-enterprise/4.2/api-vault-query.md
  content/en/docs/corda-enterprise/4.2/tutorial-attachments.md
  content/en/docs/corda-enterprise/4.3/api-vault-query.md
  content/en/docs/corda-enterprise/4.4/cordapps/api-vault-query.md
  content/en/docs/corda-enterprise/4.4/node/pki-guide.md
  content/en/docs/corda-os/1.0/api-vault-query.md
  content/en/docs/corda-os/2.0/api-vault-query.md
  content/en/docs/corda-os/3.0/api-vault-query.md
  content/en/docs/corda-os/3.1/api-vault-query.md
  content/en/docs/corda-os/3.2/api-vault-query.md
  content/en/docs/corda-os/3.3/api-vault-query.md
  content/en/docs/corda-os/3.4/api-vault-query.md
  content/en/docs/corda-os/4.0/api-vault-query.md
  content/en/docs/corda-os/4.1/api-vault-query.md
  content/en/docs/corda-os/4.3/api-vault-query.md
  content/en/docs/corda-os/4.4/api-vault-query.md
Labels: internal, team technical writing

#97 [EG-1441] Commenting back in the upgrade notes for CENM 1.2.1 patch
  content/en/docs/cenm/1.2/upgrade-notes.md
Labels: internal, team cenm

#95 [EG-2322] Fix formatting of the JMeter Samplers page
  content/en/docs/corda-enterprise/4.0/performance-testing/introduction.md
  content/en/docs/corda-enterprise/4.0/performance-testing/jmeter-samplers.md
  content/en/docs/corda-enterprise/4.0/resources/cash-issue-and-pay-sampler.png
  content/en/docs/corda-enterprise/4.0/resources/cash-issue-sampler.png
  content/en/docs/corda-enterprise/4.0/resources/cash-pay-sampler.png
  content/en/docs/corda-enterprise/4.0/resources/empty-flow-sampler.png
  content/en/docs/corda-enterprise/4.2/performance-testing/jmeter-samplers.md
  content/en/docs/corda-enterprise/4.2/resources/cash-issue-and-pay-sampler.png
  content/en/docs/corda-enterprise/4.2/resources/cash-issue-sampler.png
  content/en/docs/corda-enterprise/4.2/resources/cash-pay-sampler.png
  content/en/docs/corda-enterprise/4.2/resources/empty-flow-sampler.png
  content/en/docs/corda-enterprise/4.3/performance-testing/jmeter-samplers.md
  content/en/docs/corda-enterprise/4.3/resources/cash-issue-and-pay-sampler.png
  content/en/docs/corda-enterprise/4.3/resources/cash-issue-sampler.png
  content/en/docs/corda-enterprise/4.3/resources/cash-pay-sampler.png
  content/en/docs/corda-enterprise/4.3/resources/empty-flow-sampler.png
  content/en/docs/corda-enterprise/4.4/performance-testing/jmeter-samplers.md
Labels: internal, team technical writing

#78 ENT-5393 - document that we are not supporting redirects
  content/en/docs/corda-os/4.3/network-map.md
  content/en/docs/corda-os/4.4/network-map.md
Labels: internal, team kernel

#98 [EG-1209] Fix menu: check for missing menu entries of existing pages
  content/en/docs/corda-enterprise/4.4/api-core-types.md
  content/en/docs/corda-enterprise/4.4/building-against-non-release.md
  content/en/docs/corda-enterprise/4.4/component-library-index.md
  content/en/docs/corda-enterprise/4.4/contract-catalogue.md
  content/en/docs/corda-enterprise/4.4/contract-irs.md
  content/en/docs/corda-enterprise/4.4/contract-upgrade.md
  content/en/docs/corda-enterprise/4.4/cordapp-advanced-concepts.md
  content/en/docs/corda-enterprise/4.4/cordapps/api-contract-constraints.md
  content/en/docs/corda-enterprise/4.4/cordapps/building-a-cordapp-samples.md
  content/en/docs/corda-enterprise/4.4/docker-image.md
  content/en/docs/corda-enterprise/4.4/event-scheduling.md
  content/en/docs/corda-enterprise/4.4/financial-model.md
  content/en/docs/corda-enterprise/4.4/flow-state-machines.md
  content/en/docs/corda-enterprise/4.4/flow-testing.md
  content/en/docs/corda-enterprise/4.4/messaging.md
  content/en/docs/corda-enterprise/4.4/network/cipher-suites.md
  content/en/docs/corda-enterprise/4.4/network/corda-testnet-intro.md
  content/en/docs/corda-enterprise/4.4/network/network-map.md
  content/en/docs/corda-enterprise/4.4/node-cloud.md
  content/en/docs/corda-enterprise/4.4/node-database-intro.md
  content/en/docs/corda-enterprise/4.4/node-database-migration-logging.md
  content/en/docs/corda-enterprise/4.4/node-metrics.md
  content/en/docs/corda-enterprise/4.4/node-services.md
  content/en/docs/corda-enterprise/4.4/node/corda-firewall-component.md
  content/en/docs/corda-enterprise/4.4/node/deploy/env-dev.md
  content/en/docs/corda-enterprise/4.4/node/node-commandline.md
  content/en/docs/corda-enterprise/4.4/node/node-flow-hospital.md
  content/en/docs/corda-enterprise/4.4/node/operating/node-administration.md
  content/en/docs/corda-enterprise/4.4/node/operating/node-database-admin.md
  content/en/docs/corda-enterprise/4.4/node/operating/node-database-developer.md
  content/en/docs/corda-enterprise/4.4/node/operating/node-database-tables.md
  content/en/docs/corda-enterprise/4.4/node/operating/operating-node.md
  content/en/docs/corda-enterprise/4.4/node/pki-guide.md
  content/en/docs/corda-enterprise/4.4/node/setup/node-naming.md
  content/en/docs/corda-enterprise/4.4/node/sizing-and-performance.md
  content/en/docs/corda-enterprise/4.4/notary/faq/toctree.md
  content/en/docs/corda-enterprise/4.4/notary/ha-notary-service-overview.md
  content/en/docs/corda-enterprise/4.4/notary/ha-notary-service-setup.md
  content/en/docs/corda-enterprise/4.4/notary/installing-jpa.md
  content/en/docs/corda-enterprise/4.4/notary/notary-operate.md
  content/en/docs/corda-enterprise/4.4/performance-testing/toc-tree.md
  content/en/docs/corda-enterprise/4.4/secure-coding-guidelines.md
  content/en/docs/corda-enterprise/4.4/serialization-index.md
  content/en/docs/corda-os/4.4/building-a-cordapp-index.md
  content/en/docs/corda-os/4.4/building-against-non-release.md
Labels: internal, team technical writing

#103 ENT-5388: documenting backchainFetchBatchSize
  content/en/docs/corda-enterprise/4.4/node/setup/corda-configuration-file.md
Labels: internal, team technical writing

#100 EG-1700: Fix Table Formatting
  themes/hugo-r3-theme/layouts/shortcodes/table.html
  themes/hugo-r3-theme/package-lock.json
  themes/hugo-r3-theme/static/css/main.css
  themes/hugo-r3-theme/static/js/app.js
  themes/hugo-r3-theme/static/js/app.js.map
  themes/hugo-r3-theme/styles/scss/5_objects/_table.scss
  themes/hugo-r3-theme/styles/scss/main.scss
Labels: team application engineering, team technical writing

#104 [EG-2080] Removing cordapps tutorials samples page
  content/en/docs/corda-enterprise/4.4/cordapps/building-a-cordapp-samples.md
Labels: internal, team technical writing

#105 [EG-2769] Small fix to `crlFiles` entries in examples in idman page for CENM 1.2
  content/en/docs/cenm/1.2/identity-manager.md
Labels: internal, team cenm, team technical writing

#107 Ben-pester-EG-2043 - Update corda-configuration-file.md JarDirs warning
  content/en/docs/corda-os/4.4/corda-configuration-file.md
Labels: internal, team technical writing

#106 Eg-1660 improve checkpoint tooling documentation
  content/en/docs/corda-os/4.3/checkpoint-tooling.md
  content/en/docs/corda-os/4.4/checkpoint-tooling.md
Labels: internal, team technical writing

#108 [EG-1926] Updated nginx configuration to redirect to version 4.5 wher…
  prod/etc/nginx/conf.d/default.conf
Labels: internal, team technical writing

#111 [EG-1572/EG-2080] [Docs] Update CorDapp quickstart and dev pages
  content/en/docs/corda-enterprise/4.4/cordapps/tutorial-cordapp.md
  content/en/docs/corda-enterprise/4.5/cordapps/tutorial-cordapp.md
  content/en/docs/corda-os/4.4/tutorial-cordapp.md
  content/en/docs/corda-os/4.5/tutorial-cordapp.md
Labels: internal, team technical writing

#109 [EG-2838] Typography fix - reapplied
  themes/hugo-r3-theme/layouts/shortcodes/topic.html
  themes/hugo-r3-theme/static/css/main.css
  themes/hugo-r3-theme/static/js/app.js
  themes/hugo-r3-theme/static/js/app.js.map
  themes/hugo-r3-theme/static/js/vendor.js
  themes/hugo-r3-theme/static/js/vendor.js.map
  themes/hugo-r3-theme/styles/scss/4_base/_typography.scss
Labels: internal, team technical writing

#115 [EG-1457/EG-1582] Collect/prepare for publication the release artifacts and checksums
  content/en/docs/cenm/1.3/release-checksum-cenm.md
  content/en/docs/corda-enterprise/4.5/release-checksum-enterprise.md
  content/en/docs/corda-os/4.5/release-checksum-os.md
Labels: internal, team technical writing

#117 Update gateway-service.md EG-1122
  content/en/docs/cenm/1.3/gateway-service.md
Labels: internal, team technical writing

#116 EG-1524 - update Tokens SDK entry in release notes
  content/en/docs/corda-enterprise/4.5/release-notes-enterprise.md
  content/en/docs/corda-os/4.5/release-notes.md
Labels: internal, team technical writing

#120 Ben pester eg 1524 - back tick fix in the Ledger sync section of release notes
  content/en/docs/corda-enterprise/4.5/release-notes-enterprise.md
Labels: internal, team technical writing

#119 [EG-1143/EG-2318] Fix typo in Firewall component overview page
  content/en/docs/corda-enterprise/3.0/corda-bridge-component.md
  content/en/docs/corda-enterprise/3.1/corda-bridge-component.md
  content/en/docs/corda-enterprise/3.2/corda-bridge-component.md
  content/en/docs/corda-enterprise/3.3/corda-bridge-component.md
  content/en/docs/corda-enterprise/4.0/corda-firewall-component.md
  content/en/docs/corda-enterprise/4.2/corda-firewall-component.md
  content/en/docs/corda-enterprise/4.2/deploy/component-topology.md
  content/en/docs/corda-enterprise/4.3/corda-firewall-component.md
  content/en/docs/corda-enterprise/4.4/node/component-topology.md
  content/en/docs/corda-enterprise/4.4/node/corda-firewall-component.md
  content/en/docs/corda-enterprise/4.4/node/deploy/deploying-a-node.md
  content/en/docs/corda-enterprise/4.5/node/component-topology.md
  content/en/docs/corda-enterprise/4.5/node/corda-firewall-component.md
  content/en/docs/corda-enterprise/4.5/node/deploy/deploying-a-node.md
  content/en/docs/corda-enterprise/4.5/operations/deployment/deploying-a-node.md
Labels: internal, team technical writing

#118 Update to One-Click Deployment Page
  content/en/docs/corda-enterprise/4.5/node/deploy/oneclick-developer-test-environment.md
Labels: internal, team r3ers

#121 [EG-1206/EG-1209] Fix menu: check for missing menu entries of existing pages
  content/en/docs/corda-enterprise/4.5/corda-network/UAT.md
  content/en/docs/corda-enterprise/4.5/operations/ops-index.md
  content/en/docs/corda-enterprise/4.5/performance-testing/installation.md
  content/en/docs/corda-enterprise/4.5/performance-testing/introduction.md
  content/en/docs/corda-enterprise/4.5/performance-testing/jmeter-samplers.md
  content/en/docs/corda-enterprise/4.5/performance-testing/jmeter-testplans.md
  content/en/docs/corda-enterprise/4.5/performance-testing/performance-tuning.md
  content/en/docs/corda-enterprise/4.5/performance-testing/practical-considerations.md
  content/en/docs/corda-enterprise/4.5/performance-testing/r3-performance-runs.md
  content/en/docs/corda-enterprise/4.5/performance-testing/running-jmeter-corda.md
  content/en/docs/corda-enterprise/4.5/performance-testing/toc-tree.md
  content/en/docs/corda-os/4.5/corda-network/UAT.md
  content/en/docs/corda-os/4.5/corda-network/corda-network-foundation.md
Labels: internal, team technical writing

#122 [EG-2890] Fix to front matter of config obfuscator page
  content/en/docs/corda-enterprise/4.5/tools-config-obfuscator.md
Labels: internal, team technical writing

#126 [EG-2892] Updates to k8s deployment file [reverse propagating PR 418 on corda-docs-develop]
  content/en/docs/cenm/1.3/deployment-kubernetes.md
Labels: internal, team technical writing

#124 [EG-1164] Removes link to templates. Emphasizes license terms. Emphasizes non-p…
  content/en/docs/corda-enterprise/4.5/node/deploy/one-click-deployment.md
Labels: internal, team node internals, team r3ers, team technical writing

#127 [EG-1736] Updating JDBC session warnings in API persistence
  content/en/docs/corda-os/4.1/api-persistence.md
  content/en/docs/corda-os/4.3/api-persistence.md
  content/en/docs/corda-os/4.4/api-persistence.md
  content/en/docs/corda-os/4.5/api-persistence.md
Labels: team technical writing

#128 [EG-1292] - Fix notary metrics tables
  content/en/docs/corda-enterprise/4.2/running-a-notary-cluster/notary-metrics.md
  content/en/docs/corda-enterprise/4.3/running-a-notary-cluster/notary-metrics.md
  content/en/docs/corda-enterprise/4.4/notary/notary-metrics.md
  content/en/docs/corda-enterprise/4.5/notary/notary-metrics.md
Labels: team technical writing

#130 EG-2900: Issues in deployment section of Operations Guide
  content/en/docs/cenm/1.3/deployment-kubernetes.md
  content/en/docs/cenm/1.3/troubleshooting-common-issues.md
  content/en/docs/corda-enterprise/4.5/node-upgrade-notes.md
  content/en/docs/corda-enterprise/4.5/node/corda-firewall-configuration-file.md
  content/en/docs/corda-enterprise/4.5/node/deploy/deploying-a-node.md
  content/en/docs/corda-enterprise/4.5/node/deploy/env-prod-test.md
  content/en/docs/corda-enterprise/4.5/node/operating/cm-upgrading-node.md
  content/en/docs/corda-enterprise/4.5/operations/deployment/cenm-troubleshooting.md
  content/en/docs/corda-enterprise/4.5/operations/deployment/corda-firewall-configuration-file.md
  content/en/docs/corda-enterprise/4.5/operations/deployment/deploying-a-node.md
  content/en/docs/corda-enterprise/4.5/operations/deployment/deployment-kubernetes.md
  content/en/docs/corda-enterprise/4.5/operations/deployment/env-prod-test.md
  content/en/docs/corda-enterprise/4.5/operations/deployment/updating-network-parameters.md
Labels: documentation, internal

#129 EG-1269 - fix tables in node setup prerequisites Ent 4.4
  content/en/docs/corda-enterprise/4.4/node/setup/host-prereq.md
  content/en/docs/corda-enterprise/4.5/node/setup/host-prereq.md
Labels: internal, team technical writing

#131 EG-1143 Redirect version-less urls to latest
  prod/etc/nginx/conf.d/default.conf
Labels: internal, team technical writing

#132 [EG-1927] Updated aliases to landing index pages
  content/en/docs/cenm/1.2/_index.md
  content/en/docs/cenm/1.3/_index.md
  content/en/docs/corda-enterprise/4.4/_index.md
  content/en/docs/corda-enterprise/4.5/_index.md
  content/en/docs/corda-os/4.4/_index.md
  content/en/docs/corda-os/4.5/_index.md
Labels: internal, team technical writing

#133 [EG-2948] Adding Corda logos
  content/en/docs/corda-os/4.5/cordapp-build-systems.md
  content/en/docs/corda-os/4.5/cordapp-overview.md
  static/en/images/powered-by-corda-logo.jpg
Labels: internal, team r3ers, team technical writing

#134 EG-2326: text updated as specified in ticket
  content/en/docs/corda-enterprise/4.0/generating-a-node.md
  content/en/docs/corda-enterprise/4.1/generating-a-node.md
  content/en/docs/corda-enterprise/4.2/generating-a-node.md
  content/en/docs/corda-enterprise/4.3/generating-a-node.md
  content/en/docs/corda-enterprise/4.4/node/deploy/generating-a-node.md
Labels: internal, team technical writing

#123 [EG-2892] Propagating changes made in PR 70 from OS 4.4 to OS 4.5
  content/en/docs/corda-enterprise/4.4/node/corda-firewall-component.md
  content/en/docs/corda-enterprise/4.5/shell.md
  content/en/docs/corda-os/4.4/_index.md
  content/en/docs/corda-os/4.4/deterministic-modules.md
  content/en/docs/corda-os/4.5/aws-vm.md
  content/en/docs/corda-os/4.5/azure-vm.md
Labels: internal, team technical writing

#135 EG-2046: updating jolokia driver information
  content/en/docs/corda-enterprise/4.3/node-administration.md
  content/en/docs/corda-enterprise/4.4/node/operating/monitoring-logging.md
  content/en/docs/corda-enterprise/4.5/node/operating/node-administration.md
  content/en/docs/corda-os/4.3/node-administration.md
  content/en/docs/corda-os/4.4/node-administration.md
  content/en/docs/corda-os/4.5/node-administration.md
Labels: internal, team technical writing
