Repository corda/corda-docs, pull requests merged in 2020-08, with the labels that each got.

#184 EG-1143 Move layout parts into theme
  content/en/_index.md
  layouts/_default/README.md
  layouts/index.html
  layouts/partials/README.md
  layouts/partials/head.html
  layouts/partials/links.html
  layouts/shortcodes/README.md
  layouts/shortcodes/versions.html
  themes/hugo-r3-theme/layouts/_default/_markup/render-link.html
  themes/hugo-r3-theme/layouts/cookie-declaration/baseof.html
  themes/hugo-r3-theme/layouts/index.html
  themes/hugo-r3-theme/layouts/partials/head.html
Labels: internal

#186 EG-3479: Changing 4.4 -> 4.5
  content/en/docs/corda-enterprise/4.5/health-survey.md
  content/en/docs/corda-enterprise/4.5/node-explorer-corda-finance.md
  content/en/docs/corda-enterprise/4.5/node/deploy/deploying-a-node.md
  content/en/docs/corda-enterprise/4.5/node/deploy/env-dev.md
  content/en/docs/corda-enterprise/4.5/node/deploy/starting-components.md
  content/en/docs/corda-enterprise/4.5/node/operating/cli-application-shell-extensions.md
  content/en/docs/corda-enterprise/4.5/operations/deployment/deploying-a-node.md
  content/en/docs/corda-enterprise/4.5/operations/deployment/firewall-deployment.md
  content/en/docs/corda-enterprise/4.5/operations/deployment/generating-a-node.md
  content/en/docs/corda-enterprise/4.5/operations/deployment/starting-components.md
  content/en/docs/corda-os/4.5/cli-application-shell-extensions.md
  content/en/docs/corda-os/4.5/deploying-a-node.md
  content/en/docs/corda-os/4.5/generating-a-node.md
Labels: internal, team technical writing

#182 Fix typo in Monitoring the Corda Notary database
  content/en/docs/corda-enterprise/4.5/notary/notary-monitoring.md
Labels: external

#166 Fix tables in cipher suites pages (all relevant versions) EG-3247
  content/en/docs/corda-enterprise/3.0/cipher-suites.md
  content/en/docs/corda-enterprise/3.1/cipher-suites.md
  content/en/docs/corda-enterprise/3.2/cipher-suites.md
  content/en/docs/corda-enterprise/3.3/cipher-suites.md
  content/en/docs/corda-enterprise/4.0/cipher-suites.md
  content/en/docs/corda-enterprise/4.1/cipher-suites.md
  content/en/docs/corda-enterprise/4.2/cipher-suites.md
  content/en/docs/corda-enterprise/4.3/cipher-suites.md
  content/en/docs/corda-enterprise/4.4/network/cipher-suites.md
  content/en/docs/corda-enterprise/4.5/network/cipher-suites.md
  content/en/docs/corda-os/4.0/cipher-suites.md
  content/en/docs/corda-os/4.1/cipher-suites.md
  content/en/docs/corda-os/4.3/cipher-suites.md
  content/en/docs/corda-os/4.4/cipher-suites.md
Labels: bug, documentation, internal

#180 Update metrics description
  content/en/docs/corda-enterprise/4.5/operations/monitoring-logging/metrics-monitoring-scenarios.md
Labels: external

#191 EG-3182: correcting typo
  content/en/docs/cenm/1.0/config-pki-tool-parameters.md
  content/en/docs/cenm/1.1/config-pki-tool-parameters.md
  content/en/docs/cenm/1.2/config-pki-tool-parameters.md
  content/en/docs/cenm/1.3/config-pki-tool-parameters.md
Labels: internal, team technical writing

#196 [EG-2908/EG-3167] CE 4.4.3 Patch release - artifacts and checksums page
  content/en/docs/corda-enterprise/4.4/release-checksum-enterprise.md
  content/en/docs/corda-enterprise/4.4/release-notes-enterprise.md
  content/en/docs/corda-enterprise/4.4/release-notes-index.md
  content/en/docs/corda-enterprise/4.4/release-notes.md
  content/en/docs/corda-enterprise/4.4/resources/checksums/Corda-Enterprise-4.4.3.md
Labels: internal, team technical writing

#195 [EG-2908/EG-3166] CE 4.3.4 Patch release - artifacts and checksums page
  content/en/docs/corda-enterprise/4.3/release-checksum-enterprise.md
  content/en/docs/corda-enterprise/4.3/resources/checksums/Corda-Enterprise-4.3.4.md
Labels: internal, team technical writing

#194 [EG-2908/EG-3168] CE 4.5.1 Patch release - artifacts and checksums page
  content/en/docs/corda-enterprise/4.5/release-checksum-enterprise.md
  content/en/docs/corda-enterprise/4.5/resources/checksums/Corda-Enterprise-4.5.1.md
  content/en/docs/corda-enterprise/4.5/resources/checksums/Corda-Enterprise-4.5.md
Labels: internal, team technical writing

#197 [EG-2908/EG-3141] CENM 1.3.1 Patch release - artifacts and checksums page
  content/en/docs/cenm/1.3/release-checksum-cenm.md
  content/en/docs/cenm/1.3/resources/checksums/CENM-1.3.1.md
  content/en/docs/cenm/1.3/resources/checksums/CENM-1.3.md
Labels: internal, team technical writing

#199 [EG-2908/EG-3168] CE 4.5.1 Patch release - artifacts and checksums page
  content/en/docs/corda-enterprise/4.5/release-checksum-enterprise.md
Labels: internal, team technical writing

#198 [EG-2908/EG-3166] CE 4.3.4 Patch release - artifacts and checksums page
  content/en/docs/corda-enterprise/4.3/release-checksum-enterprise.md
Labels: internal, team technical writing

#187 EG-3162: CE 4.3.4 Patch Release Notes
  content/en/docs/corda-enterprise/4.3/release-notes-enterprise.md
Labels: internal, team technical writing

#188 EG-3164: Update release notes for 4.4.3
  content/en/docs/corda-enterprise/4.4/release-notes-enterprise.md
  content/en/docs/corda-enterprise/4.4/release-notes.md
Labels: internal, team technical writing

#189 EG-3165: updating release notes for 4.5.1
  content/en/docs/corda-enterprise/4.5/release-notes-enterprise.md
Labels: internal, team technical writing

#190 EG-3134: Updating release notes for CENM 1.3.1
  content/en/docs/cenm/1.3/release-notes.md
Labels: internal, team technical writing

#200 [EG-1572/EG-2371] Documentation: Improve clarity of state example
  content/en/docs/corda-enterprise/4.0/tutorial-contract.md
  content/en/docs/corda-enterprise/4.1/tutorial-contract.md
  content/en/docs/corda-enterprise/4.2/tutorial-contract.md
  content/en/docs/corda-enterprise/4.3/tutorial-contract.md
  content/en/docs/corda-os/4.0/tutorial-contract.md
  content/en/docs/corda-os/4.1/tutorial-contract.md
  content/en/docs/corda-os/4.3/tutorial-contract.md
  content/en/docs/corda-os/4.4/tutorial-contract.md
  content/en/docs/corda-os/4.5/tutorial-contract.md
Labels: internal, team technical writing

#201 [EG-1572/EG-3592] Missing code sample and broken links in Interacting with a node
  content/en/docs/corda-enterprise/4.4/node/operating/clientrpc.md
  content/en/docs/corda-enterprise/4.5/node/operating/clientrpc.md
Labels: internal, team technical writing

#203 [EG-1572/EG-3609] Re-name Developer Tutorials button to Corda Training
  content/en/_index.md
  themes/hugo-r3-theme/layouts/index.html
Labels: internal, team technical writing

#205 EG-3556: Fixed broken link in configuration fields page
  content/en/docs/corda-os/4.5/corda-configuration-fields.md
Labels: internal, team technical writing

#204 [EG-1572/EG-3250] Broken links to tutorials on Debugging a CorDapp page
  content/en/docs/corda-enterprise/4.0/debugging-a-cordapp.md
  content/en/docs/corda-enterprise/4.1/debugging-a-cordapp.md
  content/en/docs/corda-enterprise/4.2/debugging-a-cordapp.md
  content/en/docs/corda-enterprise/4.3/debugging-a-cordapp.md
  content/en/docs/corda-enterprise/4.4/cordapps/debugging-a-cordapp.md
  content/en/docs/corda-enterprise/4.5/cordapps/debugging-a-cordapp.md
  content/en/docs/corda-os/4.0/debugging-a-cordapp.md
  content/en/docs/corda-os/4.1/debugging-a-cordapp.md
  content/en/docs/corda-os/4.3/debugging-a-cordapp.md
  content/en/docs/corda-os/4.4/debugging-a-cordapp.md
  content/en/docs/corda-os/4.5/debugging-a-cordapp.md
Labels: internal, team technical writing

#202 [EG-3603] Adds additional guidelines around large contributions.
  content/en/docs/corda-os/4.5/contributing.md
Labels: do not merge yet!, internal, team r3ers

#206 EG-1677: Segregated network documentation for the Corda Network
  content/en/docs/corda-enterprise/4.4/corda-network/setup-segregated-notary.md
  content/en/docs/corda-enterprise/4.5/corda-network/setup-segregated-notary.md
Labels: internal, team notaries

#208 ENT-5702: Updated command line usage
  content/en/docs/corda-enterprise/4.5/node/node-commandline.md
  content/en/docs/corda-os/4.5/node-commandline.md
Labels: internal, team kernel
