Repository corda/corda-docs, pull requests merged in 2020-05, with the labels that each got.

#46 EG-1225: Add a link to cordapp-overview, fix some formatting
  content/en/docs/corda-os/4.4/release-notes.md
Labels: team technical writing

#44 EG-1441-Updated release files
  content/en/docs/cenm/1.1/release-notes.md
  content/en/docs/cenm/1.2/release-notes.md
Labels: internal, team cenm, team r3ers

#49 Removed bullet points for single sentences
  content/en/docs/cenm/1.1/release-notes.md
Labels: internal, team cenm, team technical writing

#51 [EG 1641] Adding missing platform support matrix page for CE 4.1
  content/en/docs/corda-enterprise/4.1/platform-support-matrix.md
Labels: internal, team technical writing

#53 [EG-1679] Enabled training site button on docs site home page
  layouts/index.html
Labels: internal, team technical writing

#54 [EG-1641] Fix menu entry weight for re-added platform support matrix …
  content/en/docs/corda-enterprise/4.1/platform-support-matrix.md
Labels: internal, team technical writing

#55 [EG-1679] Disabled training site button on docs site home page
  layouts/index.html
Labels: internal, team technical writing

#59 [EG-1526] Final release notes for CE 4.2.1 and CE 4.4.1
  content/en/docs/corda-enterprise/4.2/release-notes-enterprise.md
  content/en/docs/corda-enterprise/4.4/release-notes-enterprise.md
Labels: internal, team r3ers, team technical writing

#60 [EG-1526] Final release notes for CE 4.2.1 and CE 4.4.1 - more fixes
  content/en/docs/corda-enterprise/4.2/release-notes-enterprise.md
  content/en/docs/corda-enterprise/4.4/release-notes-enterprise.md
Labels: internal, team technical writing

#61 [EG-1526] Updated CE 4.4.1 version to CE 4.4.2
  content/en/docs/corda-enterprise/4.4/release-notes-enterprise.md
Labels: internal, team r3ers, team technical writing

#62 [EG-1449] Enabled Google analytics on the main docs site
  config.toml
  content/en/cookie-declaration/_index.md
Labels: internal, team technical writing

#64 [EG-1575] Configuration Obfuscator page updates for CE 4.4
  content/en/docs/corda-enterprise/4.4/node/deploy/running-a-node.md
  content/en/docs/corda-enterprise/4.4/node/deploy/starting-components.md
  content/en/docs/corda-enterprise/4.4/tools-config-obfuscator.md
Labels: internal, team node internals, team r3ers, team technical writing

#65 EG-2082: Removed Cookie banner partial
  layouts/partials/cookie-banner.html
  themes/hugo-r3-theme/static/css/main.css
  themes/hugo-r3-theme/static/js/app.js
  themes/hugo-r3-theme/static/js/app.js.map
  themes/hugo-r3-theme/static/js/vendor.js
  themes/hugo-r3-theme/static/js/vendor.js.map
Labels: internal, team r3ers

#66 EG-2119 Add performance testing to the side menu
  content/en/docs/corda-enterprise/4.4/performance-testing/installation.md
  content/en/docs/corda-enterprise/4.4/performance-testing/introduction.md
  content/en/docs/corda-enterprise/4.4/performance-testing/jmeter-samplers.md
  content/en/docs/corda-enterprise/4.4/performance-testing/jmeter-testplans.md
  content/en/docs/corda-enterprise/4.4/performance-testing/performance-tuning.md
  content/en/docs/corda-enterprise/4.4/performance-testing/practical-considerations.md
  content/en/docs/corda-enterprise/4.4/performance-testing/r3-performance-runs.md
  content/en/docs/corda-enterprise/4.4/performance-testing/running-jmeter-corda.md
  content/en/docs/corda-enterprise/4.4/performance-testing/toc-tree.md
Labels: internal, team technical writing

#57 Added CE 4.3.3 release notes
  content/en/docs/corda-enterprise/4.3/release-notes-enterprise.md
Labels: do not merge yet!, internal, team r3ers, team technical writing

#68 [EG-1679] Enable training site link on docs.corda.net home page again
  layouts/index.html
Labels: internal, team technical writing

#69 EG-2193: Switched the nav scrollbar css to 'auto'
  themes/hugo-r3-theme/layouts/partials/toc.html
  themes/hugo-r3-theme/static/css/main.css
  themes/hugo-r3-theme/static/images/svg/up-arrow.svg
  themes/hugo-r3-theme/styles/scss/6_components/_nav.scss
  themes/hugo-r3-theme/styles/scss/6_components/_toc.scss
Labels: internal

#48 EG-1733 Node Explorer documentation update
  content/en/docs/corda-enterprise/4.4/node-explorer-corda-finance.md
  content/en/docs/corda-enterprise/4.4/node-explorer.md
  content/en/docs/corda-enterprise/4.4/resources/node-explorer/node-explorer-cl-old.png
  content/en/docs/corda-enterprise/4.4/resources/node-explorer/node-explorer-cl.png
  content/en/docs/corda-enterprise/4.4/resources/node-explorer/node-explorer-dash.png
  content/en/docs/corda-enterprise/4.4/resources/node-explorer/node-explorer-flow.png
  content/en/docs/corda-enterprise/4.4/resources/node-explorer/node-explorer-map.png
  content/en/docs/corda-enterprise/4.4/resources/node-explorer/node-explorer-rpc-login.png
  content/en/docs/corda-enterprise/4.4/resources/node-explorer/node-explorer-settings-old.png
  content/en/docs/corda-enterprise/4.4/resources/node-explorer/node-explorer-settings.png
  content/en/docs/corda-enterprise/4.4/resources/node-explorer/node-explorer-ssh-login.png
  content/en/docs/corda-enterprise/4.4/resources/node-explorer/node-explorer-transactions.png
  content/en/docs/corda-enterprise/4.4/resources/node-explorer/node-explorer-vault.png
  content/en/docs/corda-os/4.4/node-explorer-corda-finance.md
  content/en/docs/corda-os/4.4/node-explorer.md
  content/en/docs/corda-os/4.4/resources/node-explorer/node-explorer-cl-old.png
  content/en/docs/corda-os/4.4/resources/node-explorer/node-explorer-cl.png
  content/en/docs/corda-os/4.4/resources/node-explorer/node-explorer-dash.png
  content/en/docs/corda-os/4.4/resources/node-explorer/node-explorer-flow.png
  content/en/docs/corda-os/4.4/resources/node-explorer/node-explorer-map.png
  content/en/docs/corda-os/4.4/resources/node-explorer/node-explorer-rpc-login.png
  content/en/docs/corda-os/4.4/resources/node-explorer/node-explorer-settings-old.png
  content/en/docs/corda-os/4.4/resources/node-explorer/node-explorer-settings.png
  content/en/docs/corda-os/4.4/resources/node-explorer/node-explorer-ssh-login.png
  content/en/docs/corda-os/4.4/resources/node-explorer/node-explorer-transactions.png
  content/en/docs/corda-os/4.4/resources/node-explorer/node-explorer-vault.png
Labels: internal, team r3ers, team technical writing

#71 EG-1572 Fix up formatting in enum evolution page
  content/en/docs/corda-os/4.4/serialization-enum-evolution.md
Labels: internal, team notaries

#70 deleted the two marketplace files - (azure and AWS)
  content/en/docs/corda-os/4.4/aws-vm.md
  content/en/docs/corda-os/4.4/azure-vm.md
Labels: internal, team technical writing

#74 [EG-2191] Fixed a link
  content/en/docs/corda-enterprise/4.4/notary/hsm-support.md
Labels: internal, team technical writing
