Repository corda/corda-docs, pull requests merged in 2020-04, with the labels that each got.

#22 More updates to the instructions in Editing Pages file
  usage-docs/editing-pages.md
Labels: internal, team technical writing

#25 EG-1512 Page titles in front-matter should be unique
  content/en/docs/corda-os/4.4/corda-nodes-index.md
Labels: team infra

#18 Minimist-fix: delete yarn.lock & package-lock.json
  themes/hugo-r3-theme/.gitignore
  themes/hugo-r3-theme/package-lock.json
  themes/hugo-r3-theme/scripts/vendor/index.js
  themes/hugo-r3-theme/static/css/main.css
  themes/hugo-r3-theme/static/js/app.js
  themes/hugo-r3-theme/static/js/app.js.map
  themes/hugo-r3-theme/static/js/mermaid.min.js
  themes/hugo-r3-theme/static/js/vendor.js
  themes/hugo-r3-theme/static/js/vendor.js.map
  themes/hugo-r3-theme/styles/scss/6_components/_attention.scss
  themes/hugo-r3-theme/webpack.config.js
  themes/hugo-r3-theme/yarn.lock
Labels: internal, team application engineering

#31 EG-1570 Make page titles unique
  themes/hugo-r3-theme/layouts/partials/meta.html
Labels: team infra, team technical writing

#30 EG-1570 Add meta description tag using hugo summary
  content/en/_index.md
  themes/hugo-r3-theme/layouts/partials/meta.html
Labels: team kernel, team technical writing

#28 EG-1567 Fix bad links
  .ci/checks/report_broken_links.py
  config.toml
  content/en/docs/corda-enterprise/3.0/demobench.md
  content/en/docs/corda-enterprise/3.0/design/float/decisions/drb-meeting-20171116.md
  content/en/docs/corda-enterprise/3.0/design/hadr/decisions/drb-meeting-20171116.md
  content/en/docs/corda-enterprise/3.0/design/hadr/decisions/near-term-target.md
  content/en/docs/corda-enterprise/3.0/design/kafka-notary/design.md
  content/en/docs/corda-enterprise/3.0/serialization.md
  content/en/docs/corda-enterprise/3.1/quickstart-index.md
  content/en/docs/corda-enterprise/3.1/serialization.md
  content/en/docs/corda-enterprise/3.2/quickstart-index.md
  content/en/docs/corda-enterprise/3.2/serialization.md
  content/en/docs/corda-enterprise/3.3/quickstart-index.md
  content/en/docs/corda-enterprise/3.3/serialization.md
  content/en/docs/corda-enterprise/4.0/cli-application-shell-extensions.md
  content/en/docs/corda-enterprise/4.0/quickstart-index.md
  content/en/docs/corda-enterprise/4.0/serialization.md
  content/en/docs/corda-enterprise/4.1/cli-application-shell-extensions.md
  content/en/docs/corda-enterprise/4.1/quickstart-index.md
  content/en/docs/corda-enterprise/4.1/serialization.md
  content/en/docs/corda-enterprise/4.2/cli-application-shell-extensions.md
  content/en/docs/corda-enterprise/4.2/quickstart-index.md
  content/en/docs/corda-enterprise/4.2/serialization.md
  content/en/docs/corda-enterprise/4.3.1/cli-application-shell-extensions.md
  content/en/docs/corda-enterprise/4.3.1/compatibility-zones.md
  content/en/docs/corda-enterprise/4.3.1/confidential-identities-hsm.md
  content/en/docs/corda-enterprise/4.3.1/serialization.md
  content/en/docs/corda-enterprise/4.4/cordapps/quickstart-build.md
  content/en/docs/corda-enterprise/4.4/database-management-tool.md
  content/en/docs/corda-enterprise/4.4/network/corda-networks.md
  content/en/docs/corda-enterprise/4.4/node/operating/confidential-identities-hsm.md
  content/en/docs/corda-enterprise/4.4/node/operating/node-database.md
  content/en/docs/corda-enterprise/4.4/node/operating/optimizing.md
  content/en/docs/corda-enterprise/4.4/notary/ha-notary-service-setup.md
  content/en/docs/corda-enterprise/4.4/serialization.md
  content/en/docs/corda-enterprise/4.4/upgrading-index.md
  content/en/docs/corda-os/1.0/serialization.md
  content/en/docs/corda-os/2.0/serialization.md
  content/en/docs/corda-os/3.0/serialization.md
  content/en/docs/corda-os/3.1/serialization.md
  content/en/docs/corda-os/3.2/serialization.md
  content/en/docs/corda-os/3.3/serialization.md
  content/en/docs/corda-os/3.4/serialization.md
  content/en/docs/corda-os/4.0/cli-application-shell-extensions.md
  content/en/docs/corda-os/4.0/quickstart-index.md
  content/en/docs/corda-os/4.0/serialization.md
  content/en/docs/corda-os/4.1/cli-application-shell-extensions.md
  content/en/docs/corda-os/4.1/quickstart-build.md
  content/en/docs/corda-os/4.1/serialization.md
  content/en/docs/corda-os/4.3/cli-application-shell-extensions.md
  content/en/docs/corda-os/4.3/serialization.md
  content/en/docs/corda-os/4.4/cli-application-shell-extensions.md
  content/en/docs/corda-os/4.4/serialization.md
Labels: team infra, team technical writing

#29 EG-1570 Fix issues flagged by SEO agency pt1
  themes/hugo-r3-theme/layouts/partials/api.html
  themes/hugo-r3-theme/layouts/partials/nav.html
  themes/hugo-r3-theme/layouts/partials/nav/r3.html
  themes/hugo-r3-theme/layouts/partials/navbar.html
  themes/hugo-r3-theme/layouts/partials/sections-tree.html
  themes/hugo-r3-theme/theme.toml
Labels: internal, team infra, team technical writing

#32 [EG-1274] Pushing comparison matrix update to CE 4.4 index page as a …
  content/en/docs/corda-enterprise/4.4/_index.md
Labels: internal, team technical writing

#34 Update corda-configuration-file.md
  content/en/docs/corda-os/4.4/corda-configuration-file.md
Labels: internal, team technical writing

#35 [EG-1605] api-flows clean up
  content/en/docs/corda-os/4.3/api-flows.md
  content/en/docs/corda-os/4.4/api-flows.md
Labels: internal, team r3ers

#41 expanded documentation of node shell output format
  content/en/docs/corda-os/4.4/shell.md
Labels: internal, team node internals
