Repository corda/corda-docs, pull requests merged in 2020-07, with the labels that each got.

#137 [EG-1143] Added redirects for generic index pages
  prod/etc/nginx/conf.d/default.conf
Labels: internal, team technical writing

#136 [EG-1143/EG-1929] UAT page is missing from Corda OS & CE 4.4 menus
  content/en/docs/corda-enterprise/4.4/corda-network/UAT.md
  content/en/docs/corda-enterprise/4.4/corda-network/the-corda-network.md
  content/en/docs/corda-enterprise/4.4/cordapps/cordapp-constraint-migration.md
  content/en/docs/corda-enterprise/4.5/cordapps/cordapp-constraint-migration.md
  content/en/docs/corda-os/4.4/corda-network/UAT.md
  content/en/docs/corda-os/4.4/corda-network/the-corda-network.md
Labels: internal, team technical writing

#138 [EG-1572/EG-2033] Blob inspector download here url
  content/en/docs/corda-os/3.3/blob-inspector.md
  content/en/docs/corda-os/3.4/blob-inspector.md
  content/en/docs/corda-os/4.0/blob-inspector.md
  content/en/docs/corda-os/4.1/blob-inspector.md
  content/en/docs/corda-os/4.3/blob-inspector.md
  content/en/docs/corda-os/4.4/blob-inspector.md
  content/en/docs/corda-os/4.5/blob-inspector.md
Labels: internal, team technical writing

#139 [EG-1572/EG-2033] Blob inspector download here url
  content/en/docs/corda-enterprise/4.1/blob-inspector.md
  content/en/docs/corda-os/3.2/blob-inspector.md
  content/en/docs/corda-os/3.3/blob-inspector.md
Labels: internal, team technical writing

#140 [EG-1572/EG-2033] Blob inspector download here url
  content/en/docs/corda-enterprise/4.1/blob-inspector.md
Labels: internal, team technical writing

#141 EG-2589: updating older versions of the documentation
  content/en/docs/corda-enterprise/4.4/docker-image.md
  content/en/docs/corda-os/4.4/docker-image.md
Labels: internal, team technical writing

#145 [EG-1585] Removed an internal TO DO note from app enterprise upgrade …
  content/en/docs/corda-enterprise/4.5/app-upgrade-notes-enterprise.md
Labels: internal, team technical writing

#143 EG-1733 updated node explorer docs to 4.5
  content/en/docs/corda-enterprise/4.4/node/node-flow-hospital.md
  content/en/docs/corda-enterprise/4.5/network/testnet-explorer.md
  content/en/docs/corda-enterprise/4.5/node-explorer.md
  content/en/docs/corda-enterprise/4.5/node/node-flow-hospital.md
  content/en/docs/corda-enterprise/4.5/resources/node-explorer/node-explorer-cl-old.png
  content/en/docs/corda-enterprise/4.5/resources/node-explorer/node-explorer-cl.png
  content/en/docs/corda-enterprise/4.5/resources/node-explorer/node-explorer-dash.png
  content/en/docs/corda-enterprise/4.5/resources/node-explorer/node-explorer-flow.png
  content/en/docs/corda-enterprise/4.5/resources/node-explorer/node-explorer-map.png
  content/en/docs/corda-enterprise/4.5/resources/node-explorer/node-explorer-rpc-login.png
  content/en/docs/corda-enterprise/4.5/resources/node-explorer/node-explorer-settings-old.png
  content/en/docs/corda-enterprise/4.5/resources/node-explorer/node-explorer-settings.png
  content/en/docs/corda-enterprise/4.5/resources/node-explorer/node-explorer-ssh-login.png
  content/en/docs/corda-enterprise/4.5/resources/node-explorer/node-explorer-transactions.png
  content/en/docs/corda-enterprise/4.5/resources/node-explorer/node-explorer-vault.png
  content/en/docs/corda-os/4.5/node-explorer.md
  content/en/docs/corda-os/4.5/resources/node-explorer/node-explorer-cl-old.png
  content/en/docs/corda-os/4.5/resources/node-explorer/node-explorer-cl.png
  content/en/docs/corda-os/4.5/resources/node-explorer/node-explorer-dash.png
  content/en/docs/corda-os/4.5/resources/node-explorer/node-explorer-flow.png
  content/en/docs/corda-os/4.5/resources/node-explorer/node-explorer-map.png
  content/en/docs/corda-os/4.5/resources/node-explorer/node-explorer-rpc-login.png
  content/en/docs/corda-os/4.5/resources/node-explorer/node-explorer-settings-old.png
  content/en/docs/corda-os/4.5/resources/node-explorer/node-explorer-settings.png
  content/en/docs/corda-os/4.5/resources/node-explorer/node-explorer-ssh-login.png
  content/en/docs/corda-os/4.5/resources/node-explorer/node-explorer-transactions.png
  content/en/docs/corda-os/4.5/resources/node-explorer/node-explorer-vault.png
  content/en/docs/corda-os/4.5/testnet-explorer-corda.md
Labels: internal, team technical writing

#144 EG-2016: bringing pages into line with Enterprise 4.5 node-administration.md
  content/en/docs/corda-enterprise/4.4/node/operating/monitoring-logging.md
  content/en/docs/corda-enterprise/4.4/node/operating/node-administration.md
  content/en/docs/corda-enterprise/4.5/node/operating/monitoring-logging.md
  content/en/docs/corda-enterprise/4.5/node/operating/node-administration.md
Labels: internal, team node internals, team technical writing

#146 [EG-3148] Fixed a bad link in OS 4.5 release notes
  content/en/docs/corda-enterprise/4.4/notary/hsm-support.md
  content/en/docs/corda-enterprise/4.5/notary/hsm-support.md
  content/en/docs/corda-os/4.5/release-notes.md
Labels: internal, team technical writing

#148 EG-3160: fixing typo
  content/en/docs/cenm/1.3/cenm-support-matrix.md
  content/en/docs/corda-enterprise/4.4/platform-support-matrix.md
  content/en/docs/corda-enterprise/4.5/operations/project-planner/cordapp-developer.md
  content/en/docs/corda-enterprise/4.5/platform-support-matrix.md
Labels: internal, team technical writing

#149 EG-3171: fixing typos
  content/en/docs/cenm/1.3/cenm-support-matrix.md
  content/en/docs/corda-enterprise/4.4/platform-support-matrix.md
  content/en/docs/corda-enterprise/4.5/operations/project-planner/cordapp-developer.md
  content/en/docs/corda-enterprise/4.5/platform-support-matrix.md
Labels: internal, team technical writing

#150 [EG-1572/EG-3157] Remove documentation for Flow Status Shell command
  content/en/docs/corda-enterprise/4.5/node/operating/querying-a-flow.md
Labels: internal, team technical writing

#151 fixed typo
  content/en/docs/corda-enterprise/4.5/metering-collector.md
Labels: internal, team node flows

#153 [EG-1457/EG-1584] Update legal-info files
  content/en/docs/cenm/1.3/legal-info.md
Labels: internal, team technical writing

#156 EG-3169: changing size of images
  content/en/docs/corda-enterprise/4.5/node/deploy/one-click-deployment.md
Labels: internal, team technical writing

#157 [EG-1457/EG-1584] Update legal-info files
  content/en/docs/cenm/1.3/legal-info.md
Labels: internal, team technical writing

#158 added changes between V1.1 and V1.2 and compatibility info.
  content/en/docs/corda-enterprise/4.5/cordapps/token-sdk-introduction.md
  content/en/docs/corda-os/4.5/token-sdk-introduction.md
Labels: internal, team external tooling, team technical writing

#161 [EG-1572/EG-3207] Minor formatting glitch in Fixed issues section
  content/en/docs/corda-enterprise/4.5/release-notes-enterprise.md
Labels: internal, team technical writing

#163 [EG-1143/EG-2299] Add missing code examples in API vault query page
  content/en/docs/corda-enterprise/4.4/cordapps/api-vault-query.md
  content/en/docs/corda-enterprise/4.5/cordapps/api-vault-query.md
  content/en/docs/corda-os/4.4/api-vault-query.md
  content/en/docs/corda-os/4.5/api-vault-query.md
Labels: internal, team technical writing

#167 [EG-3147] Adding robots.txt as part of SEO optimisation
  robots.txt
Labels: internal, team technical writing

#168 [EG-3147] moved robots.txt to the right place
  content/en/robots.txt
Labels: internal, team technical writing

#170 [EG-1572/EG-3379] Typo on the What is a CorDapp? page
  content/en/docs/corda-enterprise/3.0/cordapp-overview.md
  content/en/docs/corda-enterprise/3.1/cordapp-overview.md
  content/en/docs/corda-enterprise/3.2/cordapp-overview.md
  content/en/docs/corda-enterprise/3.3/cordapp-overview.md
  content/en/docs/corda-enterprise/4.0/cordapp-overview.md
  content/en/docs/corda-enterprise/4.1/cordapp-overview.md
  content/en/docs/corda-enterprise/4.2/cordapp-overview.md
  content/en/docs/corda-enterprise/4.3/cordapp-overview.md
  content/en/docs/corda-os/2.0/cordapp-overview.md
  content/en/docs/corda-os/3.0/cordapp-overview.md
  content/en/docs/corda-os/3.1/cordapp-overview.md
  content/en/docs/corda-os/3.2/cordapp-overview.md
  content/en/docs/corda-os/3.3/cordapp-overview.md
  content/en/docs/corda-os/3.4/cordapp-overview.md
  content/en/docs/corda-os/4.0/cordapp-overview.md
  content/en/docs/corda-os/4.1/cordapp-overview.md
  content/en/docs/corda-os/4.3/cordapp-overview.md
  content/en/docs/corda-os/4.4/cordapp-overview.md
  content/en/docs/corda-os/4.5/cordapp-overview.md
Labels: internal, team technical writing

#173 [EG-1572/EG-3251] Typos on Node identity page
  content/en/docs/corda-enterprise/3.0/node-structure.md
  content/en/docs/corda-enterprise/3.1/node-structure.md
  content/en/docs/corda-enterprise/3.2/node-structure.md
  content/en/docs/corda-enterprise/3.3/node-structure.md
  content/en/docs/corda-enterprise/4.0/node-naming.md
  content/en/docs/corda-enterprise/4.1/node-naming.md
  content/en/docs/corda-enterprise/4.2/node-naming.md
  content/en/docs/corda-enterprise/4.3/node-naming.md
  content/en/docs/corda-enterprise/4.4/node/setup/node-naming.md
  content/en/docs/corda-enterprise/4.5/node/setup/node-naming.md
  content/en/docs/corda-os/2.0/deploying-a-node.md
  content/en/docs/corda-os/3.0/generating-a-node.md
  content/en/docs/corda-os/3.1/generating-a-node.md
  content/en/docs/corda-os/3.2/generating-a-node.md
  content/en/docs/corda-os/3.3/generating-a-node.md
  content/en/docs/corda-os/3.4/generating-a-node.md
  content/en/docs/corda-os/4.0/node-naming.md
  content/en/docs/corda-os/4.1/node-naming.md
  content/en/docs/corda-os/4.3/node-naming.md
  content/en/docs/corda-os/4.4/node-naming.md
  content/en/docs/corda-os/4.5/node-naming.md
Labels: internal, team technical writing

#172 [EG-1572/EG-1503] Remove link to package ownership
  content/en/docs/corda-enterprise/4.4/node/deploy/env-dev.md
  content/en/docs/corda-enterprise/4.5/node/deploy/env-dev.md
Labels: internal, team technical writing

#175 [ENT-5395] Propagating unpropagated note regarding supported redirects
  content/en/docs/corda-enterprise/4.3/network-map.md
  content/en/docs/corda-enterprise/4.4/network/network-map.md
  content/en/docs/corda-enterprise/4.5/network/network-map.md
  content/en/docs/corda-os/4.3/network-map.md
  content/en/docs/corda-os/4.4/network-map.md
  content/en/docs/corda-os/4.5/network-map.md
Labels: team kernel, team technical writing

#177 [EG-1457-EG-3881] Update CE 4.5 artifacts and checksums info for rebuilt tools
  content/en/docs/corda-enterprise/4.5/release-checksum-enterprise.md
  content/en/docs/corda-enterprise/4.5/resources/checksums/release-checksum-enterprise.md
Labels: internal, team technical writing

#178 [EG-1572/EG-3393] Update documentation for Vault Query API - missing Spring Data JPA examples
  content/en/docs/corda-enterprise/3.0/api-vault-query.md
  content/en/docs/corda-enterprise/3.1/api-vault-query.md
  content/en/docs/corda-enterprise/3.2/api-vault-query.md
  content/en/docs/corda-enterprise/3.3/api-vault-query.md
  content/en/docs/corda-enterprise/4.0/api-vault-query.md
  content/en/docs/corda-enterprise/4.1/api-vault-query.md
  content/en/docs/corda-enterprise/4.2/api-vault-query.md
  content/en/docs/corda-enterprise/4.3/api-vault-query.md
  content/en/docs/corda-os/3.0/api-vault-query.md
  content/en/docs/corda-os/3.1/api-vault-query.md
  content/en/docs/corda-os/3.2/api-vault-query.md
  content/en/docs/corda-os/3.3/api-vault-query.md
  content/en/docs/corda-os/3.4/api-vault-query.md
  content/en/docs/corda-os/4.0/api-vault-query.md
  content/en/docs/corda-os/4.1/api-vault-query.md
  content/en/docs/corda-os/4.3/api-vault-query.md
  content/en/docs/corda-os/4.4/api-vault-query.md
  content/en/docs/corda-os/4.5/api-vault-query.md
Labels: internal, team technical writing
