Repository corda/corda-docs, pull requests merged in 2020-12, with the labels that each got.

#353 EG-4568: Update about sharing firewall with Notaries
  content/en/docs/corda-enterprise/4.6/node/corda-firewall-component.md
Labels: internal, team notaries, team technical writing

#352 [EG-2859]: Tuning section quick fix
  content/en/docs/corda-enterprise/4.5/node/setup/corda-configuration-fields.md
  content/en/docs/corda-enterprise/4.6/node/setup/corda-configuration-fields.md
Labels: internal, team technical writing

#354 EG-4353: Fixed broken links in CorDapps API testing pages.
  content/en/docs/corda-enterprise/4.4/cordapps/api-testing.md
  content/en/docs/corda-enterprise/4.5/cordapps/api-testing.md
  content/en/docs/corda-enterprise/4.6/cordapps/api-testing.md
Labels: bug, internal, team technical writing

#351 EG-4578 Add k8s storage class configuration
  content/en/docs/cenm/1.4/deployment-kubernetes.md
Labels: internal, team r3ers, team technical writing

#355 EG-4597 Fixed links in upgrade recommendation sections of CE patch release notes
  content/en/docs/corda-enterprise/3.3/release-notes.md
  content/en/docs/corda-enterprise/4.0/release-notes-enterprise.md
  content/en/docs/corda-enterprise/4.1/release-notes-enterprise.md
  content/en/docs/corda-enterprise/4.2/release-notes-enterprise.md
  content/en/docs/corda-enterprise/4.3/release-notes-enterprise.md
  content/en/docs/corda-enterprise/4.4/release-notes-enterprise.md
  content/en/docs/corda-enterprise/4.5/release-notes-enterprise.md
  content/en/docs/corda-enterprise/4.6/release-notes-enterprise.md
Labels: internal, team technical writing

#356 EG-4171: final re-arrangement of upgrade files
  content/en/docs/corda-enterprise/4.6/app-upgrade-notes-enterprise.md
  content/en/docs/corda-enterprise/4.6/app-upgrade-notes.md
  content/en/docs/corda-enterprise/4.6/node-operations-upgrade-cordapps.md
  content/en/docs/corda-enterprise/4.6/node-operations-upgrading-os-to-ent.md
  content/en/docs/corda-enterprise/4.6/node-upgrade-notes.md
  content/en/docs/corda-enterprise/4.6/node/operating/cm-backup.md
  content/en/docs/corda-enterprise/4.6/node/operating/cm-upgrading-node.md
  content/en/docs/corda-enterprise/4.6/upgrading-cordapp.md
  content/en/docs/corda-enterprise/4.6/upgrading-index.md
Labels: internal, team technical writing

#357 EG-4570: Fixed typo in command on deploying a node page.
  content/en/docs/corda-enterprise/4.6/node/deploy/deploying-a-node.md
  content/en/docs/corda-os/4.6/deploying-a-node.md
Labels: bug, internal, team technical writing

#358 EG-4603: fixing broken links introduced in EG-4171
  content/en/docs/corda-enterprise/4.6/node-database-intro.md
  content/en/docs/corda-enterprise/4.6/node-operations-upgrade-cordapps.md
  content/en/docs/corda-enterprise/4.6/node-operations-upgrading-os-to-ent.md
  content/en/docs/corda-enterprise/4.6/node/operating/node-database-developer.md
  content/en/docs/corda-enterprise/4.6/node/operating/node-database-tables.md
Labels: bug, documentation, internal, team technical writing

#361 EG-4610: removing "--core-schemas" and "--app-schemas" from the 4.5 documentation
  content/en/docs/corda-enterprise/4.5/node-upgrade-notes.md
  content/en/docs/corda-enterprise/4.5/node/operating/cm-upgrading-node.md
Labels: bug, documentation, internal, team technical writing

#362 EG-4614: tidying of upgrade menus
  config/_default/menus/menus.en.toml
  content/en/docs/corda-enterprise/4.6/app-upgrade-notes-enterprise.md
  content/en/docs/corda-enterprise/4.6/app-upgrade-notes.md
  content/en/docs/corda-enterprise/4.6/features-versions.md
  content/en/docs/corda-enterprise/4.6/node-operations-upgrading-os-to-ent.md
  content/en/docs/corda-enterprise/4.6/node-upgrade-notes.md
  content/en/docs/corda-enterprise/4.6/platform-support-matrix.md
  content/en/docs/corda-enterprise/4.6/upgrading-cordapp.md
  content/en/docs/corda-enterprise/4.6/upgrading-index.md
  content/en/docs/corda-enterprise/4.6/version-compatibility.md
Labels: internal, team technical writing

#360 EG-4601: Rearranging text and correcting link.
  content/en/docs/corda-os/4.3/node-operations-upgrade-cordapps.md
  content/en/docs/corda-os/4.4/node-operations-upgrade-cordapps.md
  content/en/docs/corda-os/4.5/node-operations-upgrade-cordapps.md
  content/en/docs/corda-os/4.6/node-operations-upgrade-cordapps.md
Labels: internal, team technical writing

#267 EG-4030 Fixes to node db admin page - Oracle sections
  content/en/docs/corda-enterprise/4.6/node/operating/node-database-admin.md
  content/en/docs/corda-enterprise/4.6/node/operating/node-database-developer.md
  content/en/docs/corda-enterprise/4.6/node/operating/node-database-tables.md
  content/en/docs/corda-enterprise/4.6/node/operating/node-database.md
  content/en/docs/corda-enterprise/4.6/node/setup/host-prereq.md
  content/en/docs/corda-enterprise/4.6/node/setup/rpc-audit-data-recording.md
  content/en/docs/corda-enterprise/4.6/operations/deployment/host-prereq.md
Labels: internal, team technical writing

#359 EG-2985: Added document that points users to relevant documentation for PKI sp…
  content/en/docs/cenm/1.2/pki-guide.md
  content/en/docs/cenm/1.2/pki-specifications.md
  content/en/docs/cenm/1.3/pki-guide.md
  content/en/docs/cenm/1.3/pki-specifications.md
  content/en/docs/cenm/1.4/pki-guide.md
  content/en/docs/cenm/1.4/pki-specifications.md
Labels: documentation, internal, team technical writing

#364 EG-4500 [ENT-6012] Update 'Querying flow data' doc page clarifying that the multi-RPC client should be aligned with the node version
  content/en/docs/corda-enterprise/4.6/node/operating/querying-flow-data.md
Labels: internal, team kernel, team technical writing

#366 EG-4633: updating operations guide
  content/en/docs/corda-enterprise/4.6/node/setup/host-prereq.md
  content/en/docs/corda-enterprise/4.6/operations/deployment/host-prereq.md
Labels: bug, internal, team technical writing

#367 EG-4030: Added missing tables to host-prereq pages.
  content/en/docs/corda-enterprise/4.6/node/setup/host-prereq.md
  content/en/docs/corda-enterprise/4.6/operations/deployment/host-prereq.md
Labels: internal

#370 EG-4638: Adding lockResolutionStrategy config option
  content/en/docs/cenm/1.5/auth-service.md
  content/en/docs/cenm/1.5/config-database.md
Labels: internal, team cenm, team technical writing

#371 EG-4050 Updated nginx redirection to point to the latest doc versions after Q4 2020 doc release
  prod/etc/nginx/conf.d/default.conf
Labels: internal, team technical writing

#373 EG-4056 Fix for BIAB version used in search
  content/en/docs/apps/bankinabox/_index.md
Labels: internal, team technical writing

#375 EG-4494 Updated state reissuance pages
  content/en/docs/corda-enterprise/4.7/cordapps/reissuing-states.md
  content/en/docs/corda-os/4.7/reissuing-states.md
Labels: internal, team technical writing

#374 EG-4102: Fix broken links
  content/en/docs/apps/bankinabox/back-end-guide.md
  content/en/docs/cdl/cdl/cdl-to-code/states-and-statuses.md
  content/en/docs/cenm/1.2/_index.md
  content/en/docs/cenm/1.5/tools-index.md
  content/en/docs/corda-enterprise/4.6/cordapps/cordapp-constraint-migration.md
  content/en/docs/corda-enterprise/4.6/notary/installing-the-notary-service.md
  content/en/docs/corda-enterprise/4.6/upgrading-cordapp.md
  content/en/docs/corda-enterprise/4.7/cordapps/reissuing-states.md
  content/en/docs/corda-enterprise/4.7/network/business-network-membership.md
  content/en/docs/corda-enterprise/4.7/node/archiving/archiving-setup.md
  content/en/docs/corda-enterprise/4.7/notary/installing-the-notary-service.md
  content/en/docs/corda-enterprise/4.7/operations/deployment/cenm-upgrade.md
  content/en/docs/corda-enterprise/4.7/operations/deployment/env-prod-test.md
  content/en/docs/corda-enterprise/4.7/upgrading-cordapp.md
  content/en/docs/corda-os/4.6/node-operations-upgrade-cordapps.md
  content/en/docs/corda-os/4.6/shell.md
  content/en/docs/corda-os/4.7/node-operations-upgrade-cordapps.md
  content/en/docs/corda-os/4.7/shell.md
Labels: internal, team technical writing

#376 EG-4647: Corrected error in login details for BIAB front end.
  content/en/docs/apps/bankinabox/user-interface/admin-ui-guide.md
Labels: bug, team technical writing
