Repository corda/corda-docs, pull requests merged in 2020-10, with the labels that each got.

#253 EG-3240-2 Updated Known Issues in CENM 1.4 release notes as per feedback [part 1]
  content/en/docs/cenm/1.4/release-notes.md
Labels: internal, team cenm, team r3ers, team technical writing

#259 EG-4013 Fixed broken links in CE 4.6 release notes
  content/en/docs/corda-enterprise/4.6/release-notes-enterprise.md
Labels: internal, team technical writing

#261 EG-3884 Doc updates relating to querying COMPLETED, FAILED, and KILLED flows
  content/en/docs/corda-enterprise/4.6/flow-start-with-client-id.md
  content/en/docs/corda-enterprise/4.6/node/operating/clientrpc.md
  content/en/docs/corda-enterprise/4.6/release-notes-enterprise.md
Labels: internal, team kernel, team technical writing

#260 EG-4014 EG-3934 Added notary serviceLegalName info + ops guide updates
  content/en/docs/corda-enterprise/4.6/node/setup/corda-configuration-fields.md
  content/en/docs/corda-enterprise/4.6/node/setup/corda-configuration-file.md
  content/en/docs/corda-enterprise/4.6/operations/deployment/corda-configuration-fields.md
  content/en/docs/corda-enterprise/4.6/operations/deployment/corda-configuration-file.md
Labels: internal, team technical writing

#263 EG-4021 Remove SMR and serviceLocationAlias refs, add plugin details
  content/en/docs/cenm/1.4/resources/example-ca-plugin-diagram.png
  content/en/docs/cenm/1.4/signing-service.md
Labels: internal, team cenm, team technical writing

#264 EG-4024 Fixed broken link on CE landing page + other fixes
  content/en/docs/cenm/1.4/_index.md
  content/en/docs/cenm/1.4/aws-deployment-guide.md
  content/en/docs/cenm/1.4/release-notes.md
  content/en/docs/cenm/1.4/signing-service.md
  content/en/docs/corda-enterprise/4.6/_index.md
  content/en/docs/corda-os/4.6/_index.md
  themes/hugo-r3-theme/layouts/index.html
Labels: internal, team technical writing

#266 EG-3361 Updated robots.txt for new release
  content/en/robots.txt
Labels: internal, team technical writing

#269 EG-2137 HA Utilities: fixed heading ordering and RHS menu and table formatting for CE 4.3-4.6
  content/en/docs/corda-enterprise/4.3/ha-utilities.md
  content/en/docs/corda-enterprise/4.4/ha-utilities.md
  content/en/docs/corda-enterprise/4.5/ha-utilities.md
  content/en/docs/corda-enterprise/4.6/ha-utilities.md
Labels: internal, team technical writing

#268 EG-4029 Added missing code examples to CE 4.4/4.5/4.6 API Transaction…
  content/en/docs/corda-enterprise/4.4/cordapps/api-transactions.md
  content/en/docs/corda-enterprise/4.5/cordapps/api-transactions.md
  content/en/docs/corda-enterprise/4.6/cordapps/api-transactions.md
Labels: internal, team technical writing

#270 EG-4033 Removed empty duplicate serviceLocation entry in Signing Service page for CENM 1.4
  content/en/docs/cenm/1.4/signing-service.md
Labels: internal, team cenm, team technical writing

#271 EG-3516: Typo fixes
  content/en/docs/corda-enterprise/4.6/notary/notary-monitoring.md
  content/en/docs/corda-enterprise/4.6/operations/monitoring-logging/metrics-monitoring-scenarios.md
Labels: team technical writing

#272 EG-4063: Fixing some links that shouldn't be links
  content/en/docs/cenm/1.3/release-notes.md
  content/en/docs/cenm/1.4/release-notes.md
Labels: team technical writing

#274 EG-4067: Fixing lots of links and typos
  content/en/docs/cenm/1.4/cenm-cli-tool.md
  content/en/docs/cenm/1.4/deployment-kubernetes-gateway.md
  content/en/docs/cenm/1.4/quick-start.md
  content/en/docs/cenm/1.4/release-notes.md
  content/en/docs/cenm/1.4/updating-network-parameters.md
  content/en/docs/cenm/1.4/upgrade-notes.md
  content/en/docs/corda-enterprise/4.1/node-operations-upgrading-os-to-ent.md
  content/en/docs/corda-enterprise/4.2/node-operations-upgrading-os-to-ent.md
  content/en/docs/corda-enterprise/4.3/node-operations-upgrading-os-to-ent.md
  content/en/docs/corda-enterprise/4.4/node/operating/node-operations-upgrading-os-to-ent.md
  content/en/docs/corda-enterprise/4.5/node/operating/node-operations-upgrading-os-to-ent.md
  content/en/docs/corda-enterprise/4.5/node/setup/corda-configuration-fields.md
  content/en/docs/corda-enterprise/4.5/operations/deployment/corda-configuration-fields.md
  content/en/docs/corda-enterprise/4.6/app-upgrade-notes.md
  content/en/docs/corda-enterprise/4.6/checkpoint-tooling.md
  content/en/docs/corda-enterprise/4.6/corda-network/setup-segregated-notary.md
  content/en/docs/corda-enterprise/4.6/cordapps/getting-set-up.md
  content/en/docs/corda-enterprise/4.6/cordapps/tutorial-cordapp.md
  content/en/docs/corda-enterprise/4.6/financial-model.md
  content/en/docs/corda-enterprise/4.6/metering-collector.md
  content/en/docs/corda-enterprise/4.6/node/collaborative-recovery/installation.md
  content/en/docs/corda-enterprise/4.6/node/collaborative-recovery/introduction-cr.md
  content/en/docs/corda-enterprise/4.6/node/collaborative-recovery/ledger-sync.md
  content/en/docs/corda-enterprise/4.6/node/corda-firewall-component.md
  content/en/docs/corda-enterprise/4.6/node/deploy/deploying-a-node.md
  content/en/docs/corda-enterprise/4.6/node/deploy/generating-a-node.md
  content/en/docs/corda-enterprise/4.6/node/deploy/running-a-node.md
  content/en/docs/corda-enterprise/4.6/node/deploy/starting-components.md
  content/en/docs/corda-enterprise/4.6/node/node-administration.md
  content/en/docs/corda-enterprise/4.6/node/operating/cm-upgrading-node.md
  content/en/docs/corda-enterprise/4.6/node/operating/ledger-graph.md
  content/en/docs/corda-enterprise/4.6/node/operating/node-database.md
  content/en/docs/corda-enterprise/4.6/node/operating/node-operations-upgrading-os-to-ent.md
  content/en/docs/corda-enterprise/4.6/node/setup/corda-configuration-fields.md
  content/en/docs/corda-enterprise/4.6/operations/deployment/corda-configuration-fields.md
  content/en/docs/corda-enterprise/4.6/operations/deployment/deployment-kubernetes-gateway.md
  content/en/docs/corda-enterprise/4.6/operations/deployment/deployment-kubernetes.md
  content/en/docs/corda-enterprise/4.6/operations/deployment/host-prereq.md
  content/en/docs/corda-enterprise/4.6/operations/deployment/running-a-node.md
  content/en/docs/corda-enterprise/4.6/operations/deployment/starting-components.md
  content/en/docs/corda-enterprise/4.6/operations/deployment/updating-network-parameters.md
  content/en/docs/corda-enterprise/4.6/operations/monitoring-logging/metrics-monitoring-scenarios.md
  content/en/docs/corda-enterprise/4.6/operations/project-planner/corda-planning.md
  content/en/docs/corda-enterprise/4.6/release-notes-enterprise.md
  content/en/docs/corda-os/4.6/api-persistence.md
  content/en/docs/corda-os/4.6/core-tutorials-index.md
  content/en/docs/corda-os/4.6/generating-a-node.md
  content/en/docs/corda-os/4.6/release-notes.md
  content/en/docs/corda-os/4.6/running-a-node.md
  content/en/docs/corda-os/4.6/supplementary-tutorials-index.md
  content/en/docs/corda-os/4.6/tutorial-cordapp.md
Labels: internal, team technical writing

#275 EG-4099 Fixed anchor links in Node Database Admin page for CE 4.4, 4.5, and 4.6
  content/en/docs/corda-enterprise/4.4/node/operating/node-database-admin.md
  content/en/docs/corda-enterprise/4.5/node/operating/node-database-admin.md
  content/en/docs/corda-enterprise/4.6/node/operating/node-database-admin.md
Labels: internal, team technical writing

#278 EG-4110 Fixed db migration steps in CE 4.6 upgrade guide
  content/en/docs/corda-enterprise/4.6/app-upgrade-notes-enterprise.md
  content/en/docs/corda-enterprise/4.6/app-upgrade-notes.md
Labels: internal, team kernel, team technical writing

#279 EG-4110 Fixed bad link
  content/en/docs/corda-enterprise/4.6/app-upgrade-notes.md
Labels: internal, team technical writing

#280 EG-3916: Updated IntelliJ and Gradle requirements.
  content/en/docs/corda-enterprise/4.5/cordapps/getting-set-up.md
  content/en/docs/corda-enterprise/4.6/cordapps/getting-set-up.md
  content/en/docs/corda-os/4.5/getting-set-up.md
  content/en/docs/corda-os/4.6/getting-set-up.md
Labels: documentation, team technical writing

#282 EG-4122: Fixing code block bug in token sdk example
  content/en/docs/corda-enterprise/4.5/cordapps/token-diamond-example.md
  content/en/docs/corda-enterprise/4.6/cordapps/token-diamond-example.md
  content/en/docs/corda-os/4.5/token-diamond-example.md
  content/en/docs/corda-os/4.6/token-diamond-example.md
Labels: team technical writing

#276 EG-4015: document the maximum character limit across the X500 name
  content/en/docs/corda-enterprise/4.0/node-naming.md
  content/en/docs/corda-enterprise/4.1/node-naming.md
  content/en/docs/corda-enterprise/4.2/node-naming.md
  content/en/docs/corda-enterprise/4.3/node-naming.md
  content/en/docs/corda-os/4.0/node-naming.md
  content/en/docs/corda-os/4.1/node-naming.md
  content/en/docs/corda-os/4.3/node-naming.md
Labels: internal, team node internals, team r3ers, team technical writing

#286 EG-4137 Added privacy@r3.com email address and contact instruction to cookie declaration
  content/en/cookie-declaration/_index.md
Labels: internal, team technical writing

#292 EG-4148: moving buttons and changing header
  content/en/_index.md
  themes/hugo-r3-theme/layouts/index.html
Labels: internal, team technical writing

#290 EG-3265: Tested, reviewed, and updated Hello, World! Tutorial in OS 4.4, 4.5.
  content/en/docs/corda-os/4.4/hello-world-flow.md
  content/en/docs/corda-os/4.4/hello-world-introduction.md
  content/en/docs/corda-os/4.4/hello-world-running.md
  content/en/docs/corda-os/4.4/hello-world-state.md
  content/en/docs/corda-os/4.4/hello-world-template.md
  content/en/docs/corda-os/4.5/hello-world-flow.md
  content/en/docs/corda-os/4.5/hello-world-introduction.md
  content/en/docs/corda-os/4.5/hello-world-running.md
  content/en/docs/corda-os/4.5/hello-world-state.md
  content/en/docs/corda-os/4.5/hello-world-template.md
Labels: internal, team technical writing

#296 EG-1629 EG-4161 Updating search config for home page to include CDL content
  themes/hugo-r3-theme/layouts/index.html
Labels: internal, team technical writing

#299 EG-4165 Update 4.6 OS & Ent New Relic licences
  content/en/docs/corda-enterprise/4.6/legal-info.md
  content/en/docs/corda-os/4.6/legal-info.md
Labels: internal, team infra, team r3ers, team technical writing

#300 EG-4165 Update pre-4.6 OS & Ent New Relic licences
  content/en/docs/corda-enterprise/4.2/legal-info.md
  content/en/docs/corda-enterprise/4.3/legal-info.md
  content/en/docs/corda-enterprise/4.4/legal-info.md
  content/en/docs/corda-enterprise/4.5/legal-info.md
  content/en/docs/corda-os/4.3/legal-info.md
  content/en/docs/corda-os/4.4/legal-info.md
  content/en/docs/corda-os/4.5/legal-info.md
Labels: internal, team infra, team r3ers, team technical writing

#298 EG-4168 Updated contributing and other pages - removed PII and updated public slack channel links
  content/en/docs/corda-os/4.0/_index.md
  content/en/docs/corda-os/4.0/aws-vm.md
  content/en/docs/corda-os/4.0/contributing-philosophy.md
  content/en/docs/corda-os/4.0/contributing.md
  content/en/docs/corda-os/4.0/getting-set-up.md
  content/en/docs/corda-os/4.0/tut-two-party-flow.md
  content/en/docs/corda-os/4.1/_index.md
  content/en/docs/corda-os/4.1/aws-vm.md
  content/en/docs/corda-os/4.1/contributing-philosophy.md
  content/en/docs/corda-os/4.1/contributing.md
  content/en/docs/corda-os/4.1/getting-set-up.md
  content/en/docs/corda-os/4.1/tut-two-party-flow.md
  content/en/docs/corda-os/4.3/_index.md
  content/en/docs/corda-os/4.3/aws-vm.md
  content/en/docs/corda-os/4.3/contributing-philosophy.md
  content/en/docs/corda-os/4.3/contributing.md
  content/en/docs/corda-os/4.3/getting-set-up.md
  content/en/docs/corda-os/4.3/tut-two-party-flow.md
  content/en/docs/corda-os/4.4/_index.md
  content/en/docs/corda-os/4.4/contributing-philosophy.md
  content/en/docs/corda-os/4.4/contributing.md
  content/en/docs/corda-os/4.4/getting-set-up.md
  content/en/docs/corda-os/4.4/tut-two-party-flow.md
  content/en/docs/corda-os/4.5/_index.md
  content/en/docs/corda-os/4.5/contributing-philosophy.md
  content/en/docs/corda-os/4.5/contributing.md
  content/en/docs/corda-os/4.5/getting-set-up.md
  content/en/docs/corda-os/4.5/tut-two-party-flow.md
  content/en/docs/corda-os/4.6/_index.md
  content/en/docs/corda-os/4.6/contributing-philosophy.md
  content/en/docs/corda-os/4.6/contributing.md
  content/en/docs/corda-os/4.6/getting-set-up.md
  content/en/docs/corda-os/4.6/tut-two-party-flow.md
Labels: internal, team technical writing

#301 EG-4167: Fixed typos, clarified ambiguous sections, tidied up formatting in up…
  content/en/docs/corda-enterprise/4.3/node-upgrade-notes.md
  content/en/docs/corda-enterprise/4.4/node-upgrade-notes.md
  content/en/docs/corda-enterprise/4.4/node/operating/cm-upgrading-node.md
  content/en/docs/corda-enterprise/4.5/node-upgrade-notes.md
  content/en/docs/corda-enterprise/4.5/node/operating/cm-upgrading-node.md
  content/en/docs/corda-enterprise/4.6/node-upgrade-notes.md
  content/en/docs/corda-enterprise/4.6/node/operating/cm-upgrading-node.md
Labels: internal, team technical writing

#283 docker pull command updated
  content/en/docs/cenm/1.3/cenm-cli-tool.md
  content/en/docs/cenm/1.3/deployment-kubernetes.md
  content/en/docs/cenm/1.4/cenm-cli-tool.md
  content/en/docs/cenm/1.4/deployment-kubernetes.md
Labels: bug, internal, team technical writing

#303 EG-4203: Fixed broken links on core tutorials index page
  content/en/docs/corda-os/4.6/core-tutorials-index.md
Labels: documentation

#304 EG-4205 Removing loose bracket in CE 4.6/4.6 testnet intro page
  content/en/docs/corda-enterprise/4.6/network/corda-testnet-intro.md
Labels: internal, team r3ers

#305 EG-4127: restructuring the config information to make it easier to un…
  content/en/docs/corda-enterprise/4.6/node/corda-firewall-configuration-file.md
  content/en/docs/corda-enterprise/4.6/operations/deployment/corda-firewall-configuration-file.md
  content/en/docs/corda-enterprise/4.6/operations/deployment/firewall-deployment.md
Labels: internal, team technical writing

#302 EG-4197 Tokens SDK: version updated inc notes on use and upgrade
  content/en/docs/corda-enterprise/4.6/cordapps/token-sdk-introduction.md
  content/en/docs/corda-enterprise/4.6/cordapps/token-selection.md
  content/en/docs/corda-os/4.6/token-sdk-introduction.md
  content/en/docs/corda-os/4.6/token-selection.md
Labels: do not merge yet!, team technical writing
