Repository corda/corda-docs, pull requests merged in 2021-05, with the labels that each got.

#468 DOC 1884 add fixes to version 4.8
  content/en/docs/corda-enterprise/4.8/cordapps/tutorial-cordapp.md
  content/en/docs/corda-os/4.8/tutorial-cordapp.md
Labels: bug, internal, team technical writing

#470 DOC-2056: Removed text that was breaking front matter
  content/en/docs/corda-os/4.8/hello-world-flow.md
Labels: bug, documentation, internal, team technical writing

#469 DOC-2024 fix example text formatting api contract constraints 4.4-4.8…
  content/en/docs/corda-enterprise/4.4/cordapps/api-contract-constraints.md
  content/en/docs/corda-enterprise/4.5/cordapps/api-contract-constraints.md
  content/en/docs/corda-enterprise/4.6/cordapps/api-contract-constraints.md
  content/en/docs/corda-enterprise/4.7/cordapps/api-contract-constraints.md
  content/en/docs/corda-enterprise/4.8/cordapps/api-contract-constraints.md
  content/en/docs/corda-os/4.4/api-contract-constraints.md
  content/en/docs/corda-os/4.5/api-contract-constraints.md
  content/en/docs/corda-os/4.6/api-contract-constraints.md
  content/en/docs/corda-os/4.7/api-contract-constraints.md
  content/en/docs/corda-os/4.8/api-contract-constraints.md
Labels: bug, internal, team technical writing

#472 DOC-2048: Removed outdated files.
  content/en/docs/corda-enterprise/4.4/cordapps/quickstart-build.md
  content/en/docs/corda-enterprise/4.4/cordapps/quickstart-deploy.md
  content/en/docs/corda-enterprise/4.4/cordapps/quickstart-index.md
  content/en/docs/corda-enterprise/4.5/cordapps/quickstart-build.md
  content/en/docs/corda-enterprise/4.5/cordapps/quickstart-deploy.md
  content/en/docs/corda-enterprise/4.5/cordapps/quickstart-index.md
  content/en/docs/corda-enterprise/4.6/cordapps/quickstart-build.md
  content/en/docs/corda-enterprise/4.6/cordapps/quickstart-deploy.md
  content/en/docs/corda-enterprise/4.6/cordapps/quickstart-index.md
  content/en/docs/corda-enterprise/4.7/cordapps/quickstart-build.md
  content/en/docs/corda-enterprise/4.7/cordapps/quickstart-deploy.md
  content/en/docs/corda-enterprise/4.7/cordapps/quickstart-index.md
  content/en/docs/corda-enterprise/4.8/cordapps/quickstart-build.md
  content/en/docs/corda-enterprise/4.8/cordapps/quickstart-deploy.md
  content/en/docs/corda-enterprise/4.8/cordapps/quickstart-index.md
  content/en/docs/corda-os/4.4/quickstart-build.md
  content/en/docs/corda-os/4.4/quickstart-index.md
  content/en/docs/corda-os/4.5/quickstart-build.md
  content/en/docs/corda-os/4.5/quickstart-deploy.md
  content/en/docs/corda-os/4.5/quickstart-index.md
  content/en/docs/corda-os/4.6/quickstart-build.md
  content/en/docs/corda-os/4.6/quickstart-deploy.md
  content/en/docs/corda-os/4.6/quickstart-index.md
  content/en/docs/corda-os/4.7/quickstart-build.md
  content/en/docs/corda-os/4.7/quickstart-deploy.md
  content/en/docs/corda-os/4.7/quickstart-index.md
  content/en/docs/corda-os/4.8/quickstart-build.md
  content/en/docs/corda-os/4.8/quickstart-deploy.md
  content/en/docs/corda-os/4.8/quickstart-index.md
Labels: bug, documentation

#451 DOC-1978 jchrisjones/fix/update-packages: All packages are at the latest
  themes/hugo-r3-theme/.eslintrc.js
  themes/hugo-r3-theme/package-lock.json
  themes/hugo-r3-theme/package.json
  themes/hugo-r3-theme/prettier.config.js
  themes/hugo-r3-theme/scripts/activate-tabs.js
  themes/hugo-r3-theme/scripts/anchorify.js
  themes/hugo-r3-theme/scripts/cookie-banner.js
  themes/hugo-r3-theme/scripts/index.js
  themes/hugo-r3-theme/scripts/nav.js
  themes/hugo-r3-theme/scripts/search-shortcut.js
  themes/hugo-r3-theme/scripts/sitemap.js
  themes/hugo-r3-theme/scripts/vendor/bootstrap-init.js
  themes/hugo-r3-theme/scripts/vendor/doc-search.js
  themes/hugo-r3-theme/scripts/vendor/googleanalytics.js
  themes/hugo-r3-theme/scripts/vendor/index.js
  themes/hugo-r3-theme/static/css/main.css
  themes/hugo-r3-theme/static/css/main.css.map
  themes/hugo-r3-theme/static/js/app.js
  themes/hugo-r3-theme/static/js/app.js.LICENSE.txt
  themes/hugo-r3-theme/static/js/app.js.map
  themes/hugo-r3-theme/static/js/vendor.js
  themes/hugo-r3-theme/static/js/vendor.js.LICENSE.txt
  themes/hugo-r3-theme/static/js/vendor.js.map
  themes/hugo-r3-theme/styles/scss/6_components/_navbar.scss
  themes/hugo-r3-theme/styles/scss/main.js
  themes/hugo-r3-theme/webpack.config.js
Labels: dependencies, do not merge yet!, internal

#475 DOC-2077 Fixes to node management console & flow management console pages
  content/en/docs/corda-enterprise/4.7/node/management-console/index.md
  content/en/docs/corda-enterprise/4.7/node/node-flow-management-console.md
  content/en/docs/corda-enterprise/4.8/node/management-console/index.md
  content/en/docs/corda-enterprise/4.8/node/node-flow-management-console.md
Labels: internal, team technical writing

#474 DOC-502: Updated the cryptoServiceTimeout parameter info in two files for CE 4.3 to 4.8
  content/en/docs/corda-enterprise/4.3/corda-configuration-file.md
  content/en/docs/corda-enterprise/4.3/cryptoservice-configuration.md
  content/en/docs/corda-enterprise/4.4/node/operating/cryptoservice-configuration.md
  content/en/docs/corda-enterprise/4.4/node/setup/corda-configuration-file.md
  content/en/docs/corda-enterprise/4.5/node/operating/cryptoservice-configuration.md
  content/en/docs/corda-enterprise/4.5/node/setup/corda-configuration-fields.md
  content/en/docs/corda-enterprise/4.5/operations/deployment/corda-configuration-fields.md
  content/en/docs/corda-enterprise/4.6/node/operating/cryptoservice-configuration.md
  content/en/docs/corda-enterprise/4.6/node/setup/corda-configuration-fields.md
  content/en/docs/corda-enterprise/4.6/operations/deployment/corda-configuration-fields.md
  content/en/docs/corda-enterprise/4.7/node/operating/cryptoservice-configuration.md
  content/en/docs/corda-enterprise/4.7/node/setup/corda-configuration-fields.md
  content/en/docs/corda-enterprise/4.7/operations/deployment/corda-configuration-fields.md
  content/en/docs/corda-enterprise/4.8/node/operating/cryptoservice-configuration.md
  content/en/docs/corda-enterprise/4.8/node/setup/corda-configuration-fields.md
Labels: bug, internal, team technical writing

#476 DOC-2045: Updated node upgrade page for CE 4.6 to 4.8
  content/en/docs/corda-enterprise/4.6/node-upgrade-notes.md
  content/en/docs/corda-enterprise/4.7/node-upgrade-notes.md
  content/en/docs/corda-enterprise/4.8/node-upgrade-notes.md
Labels: bug, internal, team technical writing

#479 Fix spring boot server command
  content/en/docs/corda-os/4.7/tutorial-cordapp.md
Labels: external

#480 DOC-2082-1 update node management console with expected behavior when…
  content/en/docs/corda-enterprise/4.7/node/management-console/index.md
  content/en/docs/corda-enterprise/4.8/node/management-console/index.md
Labels: bug, internal, team technical writing

#481 DOC-2068: Removed healthcheck command from OS docs.
  content/en/docs/corda-os/4.4/shell.md
  content/en/docs/corda-os/4.5/shell.md
  content/en/docs/corda-os/4.6/shell.md
  content/en/docs/corda-os/4.7/shell.md
  content/en/docs/corda-os/4.8/shell.md
Labels: bug, documentation
