Repository corda/corda-docs, pull requests merged in 2021-02, with the labels that each got.

#392 EG-2118: Fixed non working link to versioning on release-notes.html
  content/en/docs/corda-enterprise/4.4/release-notes.md
Labels: bug, internal, team technical writing

#394 EG-2092: On app-upgrade-notes.html part of the text fell out of the Important table
  content/en/docs/corda-enterprise/4.4/app-upgrade-notes.md
  content/en/docs/corda-enterprise/4.5/app-upgrade-notes.md
  content/en/docs/corda-enterprise/4.6/app-upgrade-notes.md
  content/en/docs/corda-enterprise/4.7/app-upgrade-notes.md
Labels: bug, internal, team technical writing

#395 EG-4699: Added some missing steps, examples, updated version numbers listed.
  content/en/docs/corda-os/4.4/building-the-docs.md
  content/en/docs/corda-os/4.5/building-the-docs.md
  content/en/docs/corda-os/4.6/building-the-docs.md
  content/en/docs/corda-os/4.7/building-the-docs.md
Labels: documentation, internal, team technical writing

#396 EG-2092-1: Fixed additional issues in app-upgrade-notes.md
  content/en/docs/corda-enterprise/4.4/app-upgrade-notes.md
  content/en/docs/corda-enterprise/4.5/app-upgrade-notes.md
  content/en/docs/corda-enterprise/4.6/app-upgrade-notes.md
  content/en/docs/corda-enterprise/4.7/app-upgrade-notes.md
Labels: bug, team technical writing

#398 EG-4704: Added a note about the sorting criteria to the Pagination section in …
  content/en/docs/corda-enterprise/4.3/api-vault-query.md
  content/en/docs/corda-enterprise/4.4/cordapps/api-vault-query.md
  content/en/docs/corda-enterprise/4.5/cordapps/api-vault-query.md
  content/en/docs/corda-enterprise/4.6/cordapps/api-vault-query.md
  content/en/docs/corda-enterprise/4.7/cordapps/api-vault-query.md
  content/en/docs/corda-os/4.3/api-vault-query.md
  content/en/docs/corda-os/4.4/api-vault-query.md
  content/en/docs/corda-os/4.5/api-vault-query.md
  content/en/docs/corda-os/4.6/api-vault-query.md
  content/en/docs/corda-os/4.7/api-vault-query.md
Labels: bug, team technical writing

#400 DOC-501: Removed link to capsule documentation, added note.
  content/en/docs/corda-enterprise/4.4/node/deploy/deploying-a-node.md
  content/en/docs/corda-enterprise/4.5/node/deploy/deploying-a-node.md
  content/en/docs/corda-enterprise/4.6/node/deploy/deploying-a-node.md
  content/en/docs/corda-enterprise/4.7/node/deploy/deploying-a-node.md
  content/en/docs/corda-os/4.4/deploying-a-node.md
  content/en/docs/corda-os/4.5/deploying-a-node.md
  content/en/docs/corda-os/4.6/deploying-a-node.md
  content/en/docs/corda-os/4.7/deploying-a-node.md
Labels: bug, internal, team technical writing

#401 DOC-1693: adding documentation on fixing RPC permissions
  content/en/docs/corda-enterprise/4.0/clientrpc.md
  content/en/docs/corda-enterprise/4.1/clientrpc.md
  content/en/docs/corda-enterprise/4.2/clientrpc.md
  content/en/docs/corda-enterprise/4.3/clientrpc.md
  content/en/docs/corda-enterprise/4.4/node/operating/clientrpc.md
  content/en/docs/corda-enterprise/4.5/node/operating/clientrpc.md
  content/en/docs/corda-enterprise/4.6/node/operating/clientrpc.md
  content/en/docs/corda-enterprise/4.7/node/operating/clientrpc.md
  content/en/docs/corda-os/4.0/clientrpc.md
  content/en/docs/corda-os/4.1/clientrpc.md
  content/en/docs/corda-os/4.3/clientrpc.md
  content/en/docs/corda-os/4.4/clientrpc.md
  content/en/docs/corda-os/4.5/clientrpc.md
  content/en/docs/corda-os/4.6/clientrpc.md
  content/en/docs/corda-os/4.7/clientrpc.md
Labels: bug, documentation, internal, team technical writing

#402 Doc 345: CorDapp constraints migration file update with a correct link
  content/en/docs/corda-enterprise/4.3/cordapp-constraint-migration.md
  content/en/docs/corda-os/4.3/cordapp-constraint-migration.md
  content/en/docs/corda-os/4.4/cordapp-constraint-migration.md
  content/en/docs/corda-os/4.5/cordapp-constraint-migration.md
  content/en/docs/corda-os/4.6/cordapp-constraint-migration.md
  content/en/docs/corda-os/4.7/cordapp-constraint-migration.md
Labels: bug, internal, team technical writing

#405 DOC-1699: Updated config-ssl.md and enm-with-ssl.md CENM files
  content/en/docs/cenm/1.2/config-ssl.md
  content/en/docs/cenm/1.2/enm-with-ssl.md
  content/en/docs/cenm/1.3/config-ssl.md
  content/en/docs/cenm/1.3/enm-with-ssl.md
  content/en/docs/cenm/1.4/config-ssl.md
  content/en/docs/cenm/1.4/enm-with-ssl.md
  content/en/docs/cenm/1.5/config-ssl.md
  content/en/docs/cenm/1.5/enm-with-ssl.md
Labels: bug, internal, team technical writing

#406 DOC-1715: Fixed error in code samples.
  content/en/docs/corda-os/4.7/tutorial-attachments.md
  content/en/docs/corda-os/4.7/tutorial-observer-nodes.md
Labels: bug, internal, team technical writing

#407 DOC-1714: Updated the database-set-up.md file for CENM 1.3, 1.4 and 1.5
  content/en/docs/cenm/1.3/database-set-up.md
  content/en/docs/cenm/1.4/database-set-up.md
  content/en/docs/cenm/1.5/database-set-up.md
Labels: bug, internal, team technical writing

#408 DOC-1720: Adding "Enterprise only" information to the Payments Alpha documentation
  content/en/docs/apps/payments/payments-index.md
Labels: bug, documentation, internal, team technical writing

#409 DOC-263-1: Updated sections Network Operations and Manual Bootstrap of the CENM deployment-kubernetes.md file
  content/en/docs/cenm/1.4/deployment-kubernetes.md
  content/en/docs/cenm/1.5/deployment-kubernetes.md
Labels: bug, internal, team technical writing

#411 DOC-1755: Clarified wording on using the same exit proof multiple times.
  content/en/docs/corda-enterprise/4.7/cordapps/reissuing-states.md
  content/en/docs/corda-os/4.7/reissuing-states.md
Labels: bug, documentation, team technical writing
