Repository corda/corda-docs, pull requests merged in 2021-03, with the labels that each got.

#414 [DOC-1778] Clarifying reference to platform version and removing references to Corda 5 and 6
  content/en/docs/corda-enterprise/4.0/versioning.md
  content/en/docs/corda-enterprise/4.1/versioning.md
  content/en/docs/corda-enterprise/4.2/versioning.md
  content/en/docs/corda-enterprise/4.3/versioning.md
  content/en/docs/corda-enterprise/4.4/cordapps/versioning.md
  content/en/docs/corda-enterprise/4.5/cordapps/versioning.md
  content/en/docs/corda-enterprise/4.6/cordapps/versioning.md
  content/en/docs/corda-enterprise/4.7/cordapps/versioning.md
  content/en/docs/corda-os/4.0/versioning.md
  content/en/docs/corda-os/4.1/versioning.md
  content/en/docs/corda-os/4.3/versioning.md
  content/en/docs/corda-os/4.4/versioning.md
  content/en/docs/corda-os/4.5/versioning.md
  content/en/docs/corda-os/4.6/versioning.md
  content/en/docs/corda-os/4.7/versioning.md
Labels: bug, team technical writing

#416 DOC-1810 Fixed a typo in CE 4.6/4.7 Corda secrets pages
  content/en/docs/corda-enterprise/4.6/secrets.md
  content/en/docs/corda-enterprise/4.7/secrets.md
Labels: bug, internal, team technical writing

#417 DOC-1795/1796/1799 - Release updates for Corda Enterprise 4.6.2
  content/en/docs/corda-enterprise/4.6/legal-info-4.6.2.md
  content/en/docs/corda-enterprise/4.6/release-checksum-enterprise.md
  content/en/docs/corda-enterprise/4.6/release-notes-enterprise.md
Labels: release patch, team technical writing

#418 DOC-1840 Added elliptic as a dependency in r3 hugo theme
  themes/hugo-r3-theme/package.json
Labels: dependencies, internal, team technical writing

#421 DOC-101 Fixed links to contributors lists in github for OS 4.4/4.7
  content/en/docs/corda-os/4.4/contributing-philosophy.md
  content/en/docs/corda-os/4.4/contributing.md
  content/en/docs/corda-os/4.5/contributing-philosophy.md
  content/en/docs/corda-os/4.5/contributing.md
  content/en/docs/corda-os/4.6/contributing-philosophy.md
  content/en/docs/corda-os/4.6/contributing.md
  content/en/docs/corda-os/4.7/contributing-philosophy.md
  content/en/docs/corda-os/4.7/contributing.md
Labels: internal, team technical writing

#422 DOC-1637 Updates to Japanese release notes for CE/OS 4.7 and CENM 1.5, plus fixes to EN versions
  content/en/docs/cenm/1.5/release-notes-ja.md
  content/en/docs/corda-enterprise/4.7/legal-info.md
  content/en/docs/corda-enterprise/4.7/release-notes-enterprise-ja.md
  content/en/docs/corda-enterprise/4.7/release-notes-enterprise.md
  content/en/docs/corda-os/4.7/release-notes-ja.md
  content/en/docs/corda-os/4.7/release-notes.md
Labels: team technical writing

#403 EG-2239 (DOC-1657): Refactor Corda OS Tutorials
  content/en/docs/corda-os/4.7/hello-world-running.md
  content/en/docs/corda-os/4.7/hello-world-state.md
  content/en/docs/corda-os/4.7/hello-world-template.md
  content/en/docs/corda-os/4.7/tut-two-party-contract.md
  content/en/docs/corda-os/4.7/tut-two-party-flow.md
  content/en/docs/corda-os/4.7/tut-two-party-introduction.md
  content/en/docs/corda-os/4.7/tutorial-cordapp.md
  content/en/docs/corda-os/4.7/tutorials-index.md
Labels: documentation, internal, team technical writing

#423 DOC-1844: Fix a broken link in the cookie declaration
  themes/hugo-r3-theme/layouts/partials/cookie-banner.html
Labels: internal, team technical writing

#424 Doc-427: Updated the sub-zones file for CENM 1.3, 1.4, and 1.5
  content/en/docs/cenm/1.3/resources/node-zone-view.png
  content/en/docs/cenm/1.3/resources/simple-seg-zones.png
  content/en/docs/cenm/1.3/resources/simple-subzones.png
  content/en/docs/cenm/1.3/sub-zones.md
  content/en/docs/cenm/1.4/resources/node-zone-view.png
  content/en/docs/cenm/1.4/resources/simple-seg-zones.png
  content/en/docs/cenm/1.4/resources/simple-subzones.png
  content/en/docs/cenm/1.4/sub-zones.md
  content/en/docs/cenm/1.5/resources/node-zone-view.png
  content/en/docs/cenm/1.5/resources/simple-seg-zones.png
  content/en/docs/cenm/1.5/resources/simple-subzones.png
  content/en/docs/cenm/1.5/sub-zones.md
Labels: bug, internal, team technical writing

#431 DOC-501: Corrected Testnet decommission date.
  content/en/docs/corda-enterprise/4.0/corda-testnet-decommission.md
  content/en/docs/corda-enterprise/4.1/corda-testnet-decommission.md
  content/en/docs/corda-enterprise/4.2/corda-testnet-decommission.md
  content/en/docs/corda-enterprise/4.3/corda-testnet-decommission.md
  content/en/docs/corda-enterprise/4.4/network/corda-testnet-decommission.md
  content/en/docs/corda-enterprise/4.5/network/corda-testnet-decommission.md
  content/en/docs/corda-enterprise/4.6/network/corda-testnet-decommission.md
  content/en/docs/corda-enterprise/4.7/network/corda-testnet-decommission.md
  content/en/docs/corda-os/4.0/deploy-to-testnet-index.md
  content/en/docs/corda-os/4.1/deploy-to-testnet-index.md
  content/en/docs/corda-os/4.3/deploy-to-testnet-index.md
  content/en/docs/corda-os/4.4/deploy-to-testnet-index.md
  content/en/docs/corda-os/4.5/deploy-to-testnet-index.md
  content/en/docs/corda-os/4.6/deploy-to-testnet-index.md
  content/en/docs/corda-os/4.7/deploy-to-testnet-index.md
Labels: documentation, internal, team technical writing

#432 DOC-359: Updated cordapp-build-systems OS and Enterprise v 4.6 and 4.7
  content/en/docs/corda-enterprise/4.6/cordapps/cordapp-build-systems.md
  content/en/docs/corda-enterprise/4.7/cordapps/cordapp-build-systems.md
  content/en/docs/corda-os/4.6/cordapp-build-systems.md
  content/en/docs/corda-os/4.7/cordapp-build-systems.md
Labels: bug, internal, team technical writing

#433 DOC-1902: Updated node-naming os and enterprise versions 4.4 through 4.7
  content/en/docs/corda-enterprise/4.4/node/setup/node-naming.md
  content/en/docs/corda-enterprise/4.5/node/setup/node-naming.md
  content/en/docs/corda-enterprise/4.6/node/setup/node-naming.md
  content/en/docs/corda-enterprise/4.7/node/setup/node-naming.md
  content/en/docs/corda-os/4.4/node-naming.md
  content/en/docs/corda-os/4.5/node-naming.md
  content/en/docs/corda-os/4.6/node-naming.md
  content/en/docs/corda-os/4.7/node-naming.md
Labels: bug, internal, team technical writing

#434 DOC-1903: updated app-upgrade-notes, checkpoint-tooling, and app-upgrade-notes-…
  content/en/docs/corda-enterprise/4.6/app-upgrade-notes-enterprise.md
  content/en/docs/corda-enterprise/4.6/checkpoint-tooling.md
  content/en/docs/corda-enterprise/4.7/app-upgrade-notes-enterprise.md
  content/en/docs/corda-enterprise/4.7/checkpoint-tooling.md
  content/en/docs/corda-os/4.6/checkpoint-tooling.md
  content/en/docs/corda-os/4.7/checkpoint-tooling.md
Labels: internal, team technical writing

#437 DOC-1802 DOC-1801 DOC-1800 Patch release CE 4.5.3 - release notes, legal-info, checksums
  content/en/docs/corda-enterprise/4.3/corda-configuration-file.md
  content/en/docs/corda-enterprise/4.3/release-notes-enterprise.md
  content/en/docs/corda-enterprise/4.4/node/setup/corda-configuration-file.md
  content/en/docs/corda-enterprise/4.4/release-notes-enterprise.md
  content/en/docs/corda-enterprise/4.5/legal-info-4.5.3.md
  content/en/docs/corda-enterprise/4.5/node/setup/corda-configuration-fields.md
  content/en/docs/corda-enterprise/4.5/operations/deployment/corda-configuration-fields.md
  content/en/docs/corda-enterprise/4.5/release-checksum-enterprise.md
  content/en/docs/corda-enterprise/4.5/release-notes-enterprise.md
  content/en/docs/corda-enterprise/4.6/node/setup/corda-configuration-fields.md
  content/en/docs/corda-enterprise/4.6/operations/deployment/corda-configuration-fields.md
  content/en/docs/corda-enterprise/4.6/release-notes-enterprise.md
Labels: internal, release patch, team technical writing

#439 DOC-1919: Fix typo in platform-support-matrix CE 4.6 version
  content/en/docs/corda-enterprise/4.6/platform-support-matrix.md
Labels: bug, internal, team technical writing
