Repository corda/corda-docs, pull requests merged in 2021-01, with the labels that each got.

#379 adding an import
  content/en/docs/corda-os/4.7/tutorial-contract.md
Labels: internal, team r3ers

#380 EG-3921: Added missing code snippets to OS 4.7 tutorials
  content/en/docs/corda-os/4.7/event-scheduling.md
  content/en/docs/corda-os/4.7/flow-state-machines.md
  content/en/docs/corda-os/4.7/flow-testing.md
  content/en/docs/corda-os/4.7/tut-two-party-contract.md
  content/en/docs/corda-os/4.7/tutorial-attachments.md
  content/en/docs/corda-os/4.7/tutorial-contract.md
  content/en/docs/corda-os/4.7/tutorial-observer-nodes.md
Labels: internal, team technical writing

#377 payments docs added
  content/en/docs/apps/_index.md
  content/en/docs/apps/bankinabox/api-guide.md
  content/en/docs/apps/bankinabox/back-end-guide.md
  content/en/docs/apps/bankinabox/bank-index.md
  content/en/docs/apps/bankinabox/getting-started.md
  content/en/docs/apps/bankinabox/user-interface/admin-ui-guide.md
  content/en/docs/apps/bankinabox/user-interface/customer-ui-guide.md
  content/en/docs/apps/bankinabox/user-interface/how-to.md
  content/en/docs/apps/bankinabox/user-interface/user-interface.md
  content/en/docs/apps/payments/modulr-payment-rail.md
  content/en/docs/apps/payments/payments-core-cordapp.md
  content/en/docs/apps/payments/payments-index.md
  content/en/docs/corda-os/4.7/release-notes.md
  themes/hugo-r3-theme/layouts/index.html
Labels: do not merge yet!, release patch, team technical writing

#381 EG-4654: Swapping ETA for backpressure terms
  content/en/docs/corda-enterprise/4.3/running-a-notary-cluster/faq/eta-mechanism.md
  content/en/docs/corda-enterprise/4.3/running-a-notary-cluster/faq/notary-failover.md
  content/en/docs/corda-enterprise/4.3/running-a-notary-cluster/faq/toctree.md
  content/en/docs/corda-enterprise/4.3/running-a-notary-cluster/ha-notary-service-setup.md
  content/en/docs/corda-enterprise/4.4/notary/faq/eta-mechanism.md
  content/en/docs/corda-enterprise/4.4/notary/faq/notary-failover.md
  content/en/docs/corda-enterprise/4.4/notary/faq/toctree.md
  content/en/docs/corda-enterprise/4.5/notary/faq/eta-mechanism.md
  content/en/docs/corda-enterprise/4.5/notary/faq/notary-failover.md
  content/en/docs/corda-enterprise/4.5/notary/faq/toctree.md
  content/en/docs/corda-enterprise/4.6/notary/faq/eta-mechanism.md
  content/en/docs/corda-enterprise/4.6/notary/faq/notary-failover.md
  content/en/docs/corda-enterprise/4.6/notary/faq/toctree.md
  content/en/docs/corda-enterprise/4.7/notary/faq/eta-mechanism.md
  content/en/docs/corda-enterprise/4.7/notary/faq/notary-failover.md
  content/en/docs/corda-enterprise/4.7/notary/faq/toctree.md
  content/en/docs/corda-enterprise/4.7/release-notes-enterprise.md
Labels: internal, team technical writing

#382 Update payments-index.md
  content/en/docs/apps/payments/payments-index.md
Labels: internal, team technical writing

#384 EG-4668: Changed BIAB guide name to How-to guide in all instances.
  content/en/docs/apps/bankinabox/user-interface/how-to.md
  content/en/docs/apps/bankinabox/user-interface/user-interface.md
  themes/hugo-r3-theme/layouts/index.html
Labels: internal, team technical writing

#385 EG-4673: Updated folder structure.
  content/en/docs/corda-os/4.7/tutorial-cordapp.md
Labels: internal, team technical writing

#387 EG-4428 Missing link on Joining a bootstrapped network page
  content/en/docs/corda-enterprise/4.4/notary/installing-the-notary-service-bootstrapper.md
  content/en/docs/corda-enterprise/4.5/notary/installing-the-notary-service-bootstrapper.md
  content/en/docs/corda-enterprise/4.6/notary/installing-the-notary-service-bootstrapper.md
  content/en/docs/corda-enterprise/4.7/notary/installing-the-notary-service-bootstrapper.md
Labels: internal, team technical writing

#389 EG-4678: updating param descriptions
  content/en/docs/corda-enterprise/4.3/corda-configuration-file.md
  content/en/docs/corda-enterprise/4.4/node/setup/corda-configuration-file.md
  content/en/docs/corda-enterprise/4.5/node/setup/corda-configuration-fields.md
  content/en/docs/corda-enterprise/4.5/operations/deployment/corda-configuration-fields.md
  content/en/docs/corda-enterprise/4.6/node/setup/corda-configuration-fields.md
  content/en/docs/corda-enterprise/4.6/operations/deployment/corda-configuration-fields.md
  content/en/docs/corda-enterprise/4.7/node/setup/corda-configuration-fields.md
  content/en/docs/corda-enterprise/4.7/operations/deployment/corda-configuration-fields.md
Labels: documentation, internal, team technical writing

#388 EG-4504: copying examples from CENM docs to CE docs (plus some link f…
  content/en/docs/cenm/1.3/pki-tool.md
  content/en/docs/cenm/1.4/pki-tool.md
  content/en/docs/cenm/1.5/pki-tool.md
  content/en/docs/corda-enterprise/4.4/pki-tool.md
  content/en/docs/corda-enterprise/4.5/pki-tool.md
  content/en/docs/corda-enterprise/4.6/pki-tool.md
  content/en/docs/corda-enterprise/4.7/pki-tool.md
Labels: bug, documentation, internal

#390 EG-4687: Fixed front matter so hello world flow page displays properly.
  content/en/docs/corda-os/4.7/hello-world-flow.md
Labels: bug, internal

#391 EG-4691: Removed references to 'production ready'. Fixed broken link. Added no…
  content/en/docs/apps/bankinabox/user-interface/admin-ui-guide.md
  content/en/docs/corda-os/4.7/release-notes.md
Labels: documentation, internal, team technical writing
