Repository corda/corda-docs, pull requests merged in 2021-04, with the labels that each got.

#442 DOC-237: backporting 4.5 bug fix info into 4.4.3 section
  content/en/docs/corda-enterprise/4.4/release-notes-enterprise.md
Labels: bug, internal

#410 DOC-1742 Cloning auth service and gateway service files
  content/en/docs/cenm/1.5/_index.md
  content/en/docs/cenm/1.5/aws-deployment-postgressql.md
  content/en/docs/cenm/1.5/cenm-cli-tool.md
  content/en/docs/cenm/1.5/cenm-console.md
  content/en/docs/cenm/1.5/database-set-up.md
  content/en/docs/cenm/1.5/deployment-kubernetes-auth.md
  content/en/docs/cenm/1.5/deployment-kubernetes-gateway.md
  content/en/docs/cenm/1.5/deployment-kubernetes.md
  content/en/docs/cenm/1.5/quick-start.md
  content/en/docs/cenm/1.5/release-notes-ja.md
  content/en/docs/cenm/1.5/release-notes.md
  content/en/docs/cenm/1.5/signing-service.md
  content/en/docs/cenm/1.5/upgrade-notes.md
  content/en/docs/cenm/1.5/user-admin.md
  content/en/docs/cenm/1.5/zone-service.md
  content/en/docs/corda-enterprise/4.7/node/auth-service.md
  content/en/docs/corda-enterprise/4.7/node/azure-ad-sso/_index.md
  content/en/docs/corda-enterprise/4.7/node/azure-ad-sso/step1.png
  content/en/docs/corda-enterprise/4.7/node/azure-ad-sso/step10.png
  content/en/docs/corda-enterprise/4.7/node/azure-ad-sso/step11.png
  content/en/docs/corda-enterprise/4.7/node/azure-ad-sso/step12.png
  content/en/docs/corda-enterprise/4.7/node/azure-ad-sso/step13.png
  content/en/docs/corda-enterprise/4.7/node/azure-ad-sso/step14.png
  content/en/docs/corda-enterprise/4.7/node/azure-ad-sso/step15.png
  content/en/docs/corda-enterprise/4.7/node/azure-ad-sso/step2.png
  content/en/docs/corda-enterprise/4.7/node/azure-ad-sso/step3.png
  content/en/docs/corda-enterprise/4.7/node/azure-ad-sso/step4.png
  content/en/docs/corda-enterprise/4.7/node/azure-ad-sso/step5.png
  content/en/docs/corda-enterprise/4.7/node/azure-ad-sso/step6.png
  content/en/docs/corda-enterprise/4.7/node/azure-ad-sso/step7.png
  content/en/docs/corda-enterprise/4.7/node/azure-ad-sso/step8.png
  content/en/docs/corda-enterprise/4.7/node/azure-ad-sso/step9.png
  content/en/docs/corda-enterprise/4.7/node/gateway-service.md
  content/en/docs/corda-enterprise/4.7/node/management-console/_index.md
  content/en/docs/corda-enterprise/4.7/node/node-flow-management-console.md
  content/en/docs/corda-enterprise/4.7/operations/deployment/deployment-kubernetes-auth.md
  content/en/docs/corda-enterprise/4.7/operations/deployment/deployment-kubernetes-gateway.md
  content/en/docs/corda-enterprise/4.7/operations/deployment/deployment-kubernetes.md
  content/en/docs/corda-enterprise/4.7/release-notes-enterprise-ja.md
  content/en/docs/corda-enterprise/4.7/release-notes-enterprise.md
Labels: internal, team application engineering, team cenm, team technical writing

#446 DOC-270: Amended node documentation to make clear '+' character is not supported in the X500 name
  content/en/docs/corda-enterprise/4.3/node-naming.md
  content/en/docs/corda-enterprise/4.4/node/setup/node-naming.md
  content/en/docs/corda-enterprise/4.5/node/setup/node-naming.md
  content/en/docs/corda-enterprise/4.6/node/setup/node-naming.md
  content/en/docs/corda-enterprise/4.7/node/setup/node-naming.md
  content/en/docs/corda-os/4.3/node-naming.md
  content/en/docs/corda-os/4.4/node-naming.md
  content/en/docs/corda-os/4.5/node-naming.md
  content/en/docs/corda-os/4.6/node-naming.md
  content/en/docs/corda-os/4.7/node-naming.md
Labels: bug, internal, team technical writing

#448 DOC-1953: Add links to CE ops page
  content/en/docs/corda-enterprise/4.5/operations/ops-index.md
  content/en/docs/corda-enterprise/4.6/operations/ops-index.md
  content/en/docs/corda-enterprise/4.7/operations/ops-index.md
Labels: bug, internal, team technical writing

#443 Several fixes
  content/en/docs/corda-os/4.7/hello-world-running.md
  content/en/docs/corda-os/4.7/tutorial-cordapp.md
Labels: external

#444 DOC-1932: Updates to reflect changes to CENM User Admin Tool UI
  content/en/docs/cenm/1.5/resources/create_group_new.png
  content/en/docs/cenm/1.5/resources/create_role_new.png
  content/en/docs/cenm/1.5/resources/create_user_new.png
  content/en/docs/cenm/1.5/resources/group_details_new.png
  content/en/docs/cenm/1.5/resources/groups_list_new.png
  content/en/docs/cenm/1.5/resources/role_details_new.png
  content/en/docs/cenm/1.5/resources/roles_list_new.png
  content/en/docs/cenm/1.5/resources/user_details_new.png
  content/en/docs/cenm/1.5/resources/users_list_new.png
  content/en/docs/cenm/1.5/user-admin.md
Labels: do not merge yet!, internal, team technical writing

#452 DOC-1834 Patch release CENM 1.5.1 - release notes, legal-info, checksums, AWS CloudHSM & Oracle 19c version bump updates
  content/en/docs/cenm/1.5/aws-deployment-hsm-aws-console.md
  content/en/docs/cenm/1.5/cenm-support-matrix.md
  content/en/docs/cenm/1.5/database-set-up.md
  content/en/docs/cenm/1.5/enm-with-ssl.md
  content/en/docs/cenm/1.5/legal-info-1.5.0.md
  content/en/docs/cenm/1.5/legal-info-1.5.1.md
  content/en/docs/cenm/1.5/pki-tool.md
  content/en/docs/cenm/1.5/release-checksum-cenm.md
  content/en/docs/cenm/1.5/release-notes.md
  content/en/docs/cenm/1.5/signing-service.md
  themes/hugo-r3-theme/layouts/index.html
Labels: do not merge yet!, internal, release patch, team cenm, team technical writing

#456 DOC-1860: fixing broken links in pre-4.8 releases
  content/en/docs/cenm/1.5/user-admin.md
  content/en/docs/corda-enterprise/4.6/cordapps/quickstart-build.md
  content/en/docs/corda-enterprise/4.6/cordapps/tutorial-cordapp.md
  content/en/docs/corda-enterprise/4.6/cordapps/upgrading-cordapps.md
  content/en/docs/corda-enterprise/4.7/cordapps/quickstart-build.md
  content/en/docs/corda-enterprise/4.7/cordapps/tutorial-cordapp.md
  content/en/docs/corda-enterprise/4.7/cordapps/upgrading-cordapps.md
  content/en/docs/corda-enterprise/4.7/network/testnet-decommission.md
Labels: documentation, team technical writing

#457 DOC-1875: fixing broken links
  content/en/docs/corda-enterprise/4.7/cordapps/cordapp-constraint-migration.md
  content/en/docs/corda-enterprise/4.7/cordapps/cordapp-upgradeability.md
Labels: internal, team technical writing

#459 DOC-1871 Updating some links in CENM 1.5 doc set to point to the latest 4.8 doc pages.
  content/en/docs/cenm/1.5/_index.md
  content/en/docs/cenm/1.5/aws-deployment-postgressql.md
  content/en/docs/cenm/1.5/cenm-cli-tool.md
  content/en/docs/cenm/1.5/cenm-console.md
  content/en/docs/cenm/1.5/cenm-error-codes.md
  content/en/docs/cenm/1.5/cenm-support-matrix.md
  content/en/docs/cenm/1.5/config-network-parameters.md
  content/en/docs/cenm/1.5/database-set-up.md
  content/en/docs/cenm/1.5/deployment-kubernetes-auth.md
  content/en/docs/cenm/1.5/deployment-kubernetes-gateway.md
  content/en/docs/cenm/1.5/deployment-kubernetes.md
  content/en/docs/cenm/1.5/quick-start.md
  content/en/docs/cenm/1.5/signing-service.md
  content/en/docs/cenm/1.5/tools-index.md
  content/en/docs/cenm/1.5/updating-network-parameters.md
  content/en/docs/cenm/1.5/user-admin.md
  content/en/docs/cenm/1.5/zone-service.md
  content/en/docs/corda-enterprise/4.7/node/auth-service.md
  content/en/docs/corda-enterprise/4.7/node/gateway-service.md
Labels: internal, release quarterly, team technical writing

#461 DOC-935 Reordering of LHS menu for 4.8 release
  content/en/docs/cenm/1.5/_index.md
  content/en/docs/corda-enterprise/4.7/_index.md
  content/en/docs/corda-os/4.7/_index.md
  content/en/docs/corda-os/4.8/_index.md
Labels: internal, release quarterly, team technical writing

#462 DOC-2008: fixing broken links
  content/en/docs/corda-enterprise/4.5/node/setup/corda-configuration-fields.md
  content/en/docs/corda-enterprise/4.5/operations/deployment/corda-configuration-fields.md
  content/en/docs/corda-enterprise/4.6/cordapps/cordapp-upgradeability.md
  content/en/docs/corda-enterprise/4.6/flow-state-machines.md
  content/en/docs/corda-enterprise/4.6/node/operating/node-database-developer.md
  content/en/docs/corda-enterprise/4.6/node/setup/corda-configuration-fields.md
  content/en/docs/corda-enterprise/4.6/operations/deployment/corda-configuration-fields.md
  content/en/docs/corda-enterprise/4.7/flow-state-machines.md
  content/en/docs/corda-enterprise/4.7/node/operating/ledger-graph.md
  content/en/docs/corda-enterprise/4.7/node/operating/node-database-developer.md
  content/en/docs/corda-enterprise/4.7/node/setup/corda-configuration-fields.md
  content/en/docs/corda-enterprise/4.7/operations/deployment/corda-configuration-fields.md
  content/en/docs/corda-enterprise/4.8/node/operating/ledger-graph.md
  content/en/docs/corda-enterprise/4.8/node/operating/node-database-developer.md
  content/en/docs/corda-enterprise/4.8/node/setup/corda-configuration-fields.md
  content/en/docs/corda-enterprise/4.8/operations/deployment/corda-configuration-fields.md
Labels: bug, internal, team technical writing

#438 DOC-1884 updates to file tutorial-cordapp
  content/en/docs/corda-enterprise/4.4/cordapps/tutorial-cordapp.md
  content/en/docs/corda-enterprise/4.5/cordapps/tutorial-cordapp.md
  content/en/docs/corda-enterprise/4.6/cordapps/tutorial-cordapp.md
  content/en/docs/corda-enterprise/4.7/cordapps/tutorial-cordapp.md
  content/en/docs/corda-os/4.4/tutorial-cordapp.md
  content/en/docs/corda-os/4.5/tutorial-cordapp.md
  content/en/docs/corda-os/4.6/tutorial-cordapp.md
  content/en/docs/corda-os/4.7/tutorial-cordapp.md
Labels: bug, do not merge yet!, internal, team technical writing

#463 DOC-2018 add missing PKI config examples
  content/en/docs/corda-enterprise/4.8/pki-tool.md
Labels: bug, internal, team technical writing

#464 Doc 2017 updated version numbers in ledger graph and archive service docs v4.7.1 and 4.8
  content/en/docs/corda-enterprise/4.7/node/archiving/archiving-cli.md
  content/en/docs/corda-enterprise/4.7/node/archiving/archiving-setup.md
  content/en/docs/corda-enterprise/4.7/node/operating/ledger-graph.md
  content/en/docs/corda-enterprise/4.8/node/archiving/archiving-cli.md
  content/en/docs/corda-enterprise/4.8/node/archiving/archiving-setup.md
  content/en/docs/corda-enterprise/4.8/node/operating/ledger-graph.md
Labels: documentation

#454 DOC-120: Update Corda PV page to reflect changes from v4.4 on
  content/en/docs/corda-enterprise/4.4/features-versions.md
  content/en/docs/corda-enterprise/4.5/cordapps/versioning.md
  content/en/docs/corda-enterprise/4.5/features-versions.md
  content/en/docs/corda-enterprise/4.6/cordapps/versioning.md
  content/en/docs/corda-enterprise/4.6/features-versions.md
  content/en/docs/corda-enterprise/4.7/cordapps/versioning.md
  content/en/docs/corda-enterprise/4.7/features-versions.md
  content/en/docs/corda-enterprise/4.8/cordapps/versioning.md
  content/en/docs/corda-enterprise/4.8/features-versions.md
  content/en/docs/corda-os/4.4/features-versions.md
  content/en/docs/corda-os/4.4/versioning.md
  content/en/docs/corda-os/4.5/features-versions.md
  content/en/docs/corda-os/4.5/versioning.md
  content/en/docs/corda-os/4.6/features-versions.md
  content/en/docs/corda-os/4.6/versioning.md
  content/en/docs/corda-os/4.7/features-versions.md
  content/en/docs/corda-os/4.7/versioning.md
  content/en/docs/corda-os/4.8/features-versions.md
  content/en/docs/corda-os/4.8/versioning.md
Labels: bug, do not merge yet!, internal, team technical writing

#465 DOC-2022: Removing escape characters from node doc
  content/en/docs/corda-enterprise/4.8/node-metrics.md
Labels: internal, team technical writing

#466 DOC-2005: fixing missing link
  content/en/docs/corda-enterprise/4.4/cordapp-advanced-concepts.md
  content/en/docs/corda-enterprise/4.5/cordapp-advanced-concepts.md
  content/en/docs/corda-enterprise/4.6/cordapp-advanced-concepts.md
  content/en/docs/corda-enterprise/4.7/cordapp-advanced-concepts.md
  content/en/docs/corda-enterprise/4.8/cordapp-advanced-concepts.md
Labels: bug, documentation, internal, team technical writing

#467 DOC-2046: Fixed broken links.
  content/en/docs/corda-os/4.8/core-tutorials-index.md
Labels: bug, documentation, internal
