Repository corda/corda-docs, pull requests merged in 2021-06, with the labels that each got.

#484 DOC-2190: Fixed spelling mistake in release notes.
  content/en/docs/corda-enterprise/4.4/release-notes.md
  content/en/docs/corda-os/4.3/release-notes.md
  content/en/docs/corda-os/4.4/release-notes.md
  content/en/docs/corda-os/4.5/release-notes.md
  content/en/docs/corda-os/4.6/release-notes.md
  content/en/docs/corda-os/4.7/release-notes.md
  content/en/docs/corda-os/4.8/release-notes.md
Labels: bug, documentation

#483 DOC 2126: Writing a CorDapp using a template tutorials rewrite
  content/en/docs/corda-os/4.8/_index.md
  content/en/docs/corda-os/4.8/hello-world-running.md
  content/en/docs/corda-os/4.8/hello-world-template.md
  content/en/docs/corda-os/4.8/modify-the-flow.md
  content/en/docs/corda-os/4.8/modify-the-state.md
  content/en/docs/corda-os/4.8/obtain-the-cordapp-template.md
  content/en/docs/corda-os/4.8/run-your-cordapp.md
  content/en/docs/corda-os/4.8/tut-two-party-contract.md
  content/en/docs/corda-os/4.8/tut-two-party-flow.md
  content/en/docs/corda-os/4.8/tut-two-party-introduction.md
  content/en/docs/corda-os/4.8/writing-a-cordapp-using-a-template.md
  themes/hugo-r3-theme/layouts/index.html
Labels: do not merge yet!, documentation, team technical writing

#486 DOC-2230: Fixed typo on CDL overview page
  content/en/docs/cdl/cdl/cdl-overview.md
Labels: bug, documentation, internal

#485 DOC-2229: Corrected indentation in extraConfig section of notary configuration …
  content/en/docs/corda-enterprise/4.5/node/setup/corda-configuration-fields.md
  content/en/docs/corda-enterprise/4.5/operations/deployment/corda-configuration-fields.md
  content/en/docs/corda-enterprise/4.6/node/setup/corda-configuration-fields.md
  content/en/docs/corda-enterprise/4.6/operations/deployment/corda-configuration-fields.md
  content/en/docs/corda-enterprise/4.7/node/setup/corda-configuration-fields.md
  content/en/docs/corda-enterprise/4.7/operations/deployment/corda-configuration-fields.md
  content/en/docs/corda-enterprise/4.8/node/setup/corda-configuration-fields.md
  content/en/docs/corda-enterprise/4.8/operations/deployment/corda-configuration-fields.md
Labels: bug, documentation

#487 DOC-2247: Fixed broken links.
  content/en/docs/corda-enterprise/4.4/corda-network/UAT.md
  content/en/docs/corda-enterprise/4.5/corda-network/UAT.md
  content/en/docs/corda-enterprise/4.6/corda-network/UAT.md
  content/en/docs/corda-enterprise/4.7/corda-network/UAT.md
  content/en/docs/corda-enterprise/4.8/corda-network/UAT.md
Labels: bug, documentation, internal

#489 DOC-2210: fixing release notes
  content/en/docs/corda-enterprise/4.7/release-notes-enterprise.md
Labels: bug, documentation, internal

#455 DOC-1922 Changes to links to http://slack.corda.net
  config.toml
  content/en/docs/corda-enterprise/3.0/getting-set-up.md
  content/en/docs/corda-enterprise/3.1/getting-set-up.md
  content/en/docs/corda-enterprise/3.2/getting-set-up.md
  content/en/docs/corda-enterprise/3.3/getting-set-up.md
  content/en/docs/corda-enterprise/4.0/getting-set-up.md
  content/en/docs/corda-enterprise/4.1/getting-set-up.md
  content/en/docs/corda-enterprise/4.2/getting-set-up.md
  content/en/docs/corda-enterprise/4.3/getting-set-up.md
  content/en/docs/corda-enterprise/4.4/cordapps/getting-set-up.md
  content/en/docs/corda-enterprise/4.5/cordapps/getting-set-up.md
  content/en/docs/corda-enterprise/4.6/cordapps/getting-set-up.md
  content/en/docs/corda-enterprise/4.7/cordapps/getting-set-up.md
  content/en/docs/corda-enterprise/4.8/cordapps/getting-set-up.md
  content/en/docs/corda-os/1.0/getting-set-up.md
  content/en/docs/corda-os/2.0/getting-set-up.md
  content/en/docs/corda-os/3.0/contributing.md
  content/en/docs/corda-os/3.0/getting-set-up.md
  content/en/docs/corda-os/3.1/contributing.md
  content/en/docs/corda-os/3.1/getting-set-up.md
  content/en/docs/corda-os/3.2/contributing.md
  content/en/docs/corda-os/3.2/getting-set-up.md
  content/en/docs/corda-os/3.3/contributing.md
  content/en/docs/corda-os/3.3/getting-set-up.md
  content/en/docs/corda-os/3.4/contributing.md
  content/en/docs/corda-os/3.4/getting-set-up.md
Labels: bug, do not merge yet!, internal, team technical writing
