Repository corda/corda-docs, pull requests merged in 2021-07, with the labels that each got.

#488 Doc 2254 - propagate rewritten CorDapp tutorial from portal to docs site
  content/en/docs/corda-enterprise/4.8/cordapps/tutorial-cordapp.md
  content/en/docs/corda-os/4.8/tutorial-cordapp.md
Labels: bug, internal, team technical writing

#490 DOC-2291 Remove inaccuracies on Corda and Corda Enterprise compatibility
  content/en/docs/corda-enterprise/4.0/version-compatibility.md
  content/en/docs/corda-enterprise/4.1/version-compatibility.md
  content/en/docs/corda-enterprise/4.2/version-compatibility.md
  content/en/docs/corda-enterprise/4.3/version-compatibility.md
  content/en/docs/corda-enterprise/4.4/version-compatibility.md
  content/en/docs/corda-enterprise/4.5/version-compatibility.md
  content/en/docs/corda-enterprise/4.6/version-compatibility.md
  content/en/docs/corda-enterprise/4.7/version-compatibility.md
  content/en/docs/corda-enterprise/4.8/version-compatibility.md
Labels: bug, documentation

#491 DOC-2049 Changed link in HSM support for notaries for versions 4.8 to…
  content/en/docs/corda-enterprise/4.5/notary/hsm-support.md
  content/en/docs/corda-enterprise/4.6/notary/hsm-support.md
  content/en/docs/corda-enterprise/4.7/notary/hsm-support.md
  content/en/docs/corda-enterprise/4.8/notary/hsm-support.md
Labels: bug, internal, team technical writing

#494 DOC-2891: Fixed broken links.
  content/en/docs/corda-os/4.8/core-tutorials-index.md
  content/en/docs/corda-os/4.8/tutorial-cordapp.md
Labels: bug, documentation

#436 DOC-144: adding information about Kubernetes Dashboard
  content/en/docs/cenm/1.5/deployment-kubernetes.md
  content/en/docs/corda-enterprise/4.7/operations/deployment/deployment-kubernetes.md
  content/en/docs/corda-enterprise/4.8/operations/deployment/deployment-kubernetes.md
Labels: bug, documentation, internal, team cenm, team technical writing

#477 DOC-412 How to add a new notary after the network map is running & ho…
  content/en/docs/cenm/1.2/updating-network-parameters.md
  content/en/docs/corda-enterprise/4.6/network/network-map.md
  content/en/docs/corda-enterprise/4.7/network/network-map.md
  content/en/docs/corda-os/4.6/network-map.md
Labels: bug, internal, team technical writing

#496 NOTICK: Use Artifactory as Docker cache
  Dockerfile
  makefile
Labels: internal, team infra
